### ISSUE TITLE
LogError parameters reversed 

### ISSUE THREAD

**Issue by jhulbertpmn** [Azure/azure-functions-servicebus-extension#101]
https://github.com/Azure/azure-functions-servicebus-extension/blob/8a01c68d16c5eeeda80010fd32f34d265eca9534/src/Microsoft.Azure.WebJobs.Extensions.ServiceBus/Listeners/ServiceBusListener.cs#L315

I was receiving "An unhandled exception occurred in the message batch receive loop" in my function app and couldn't see why (in searching for others with the issue I came upon some suggestions of changes to prefetch count and others settings but none seemed to resolve my issue). I turned logging up to trace but still wasn't getting detail for this exception, and I noticed looking in the source here that the function call to LogError has two parameters - the message string above and the exception. However, the LogError function overload that actually ends up resolving to is the one that takes a string template and parameters, and the string doesn't use any parameters in it. 

I downloaded the source for this project, referenced that in my project instead of the nuget package and changed that line to:

_logger.LogError(ex, "An unhandled exception occurred in the message batch receive loop");

and I started receiving the detail I expected (turns out I had a type in my queue name - doh!

**Comment by jdimmerman** [comment]
This looks like the same issue as https://github.com/Azure/azure-functions-servicebus-extension/issues/97 and its associated PR.

Small change with major consequences. @soninaren - Is there a timeline on this?

Thanks!

**Comment by alrod** [comment]
Fix is merged.
