### ISSUE TITLE
Support for the new ServiceBus SDK

### ISSUE THREAD

**Issue by mauve** [Azure/azure-functions-servicebus-extension#103]
Hi,

Is there a way to use the new ServiceBus SDK with Azure functions?

I really would like to get rid of my connection strings in my functions.

Kind regards,

Mikael

**Comment by pragnagopa** [comment]
cc @soninaren @sidkri 

@mauve  - which version are you looking for?

**Comment by mauve** [comment]
I am mostly interested in starting to use the SDKs which support Azure.Identity. Those should be the SDKs whose .NET pacakge names start with Azure.* instead of Microsoft.Azure.* (if I understand correctly).

In general I am interested to know this for all bindings/triggers and the host but unsure which github repo I should post my bug to, I have also created this bug: https://github.com/Azure/azure-webjobs-sdk/issues/2575

**Comment by SeanFeldman** [comment]
Shouldn't Functions first support authentication such as MSI first before it can take a dependency on the track 2 ASB client?
Also, track 2 client is not GA-ed yet.

**Comment by mauve** [comment]
What does "track 2" mean? I assume that you mean the new SDKs by that.

The fact that they are not GA right now is not important. They will eventually become GA:d.

**Comment by SeanFeldman** [comment]
> What does "track 2" mean?

https://weblogs.asp.net/sfeldman/the-future-of-asb-dotnet-sdk

> The fact that they are not GA right now is not important. They will eventually become GA:d.

It's a preview package so breaking changes are common. Some organizations/teams can decide they do not invest in work until the package is stable.

**Comment by SeanFeldman** [comment]
Raised a specific issue #128

**Comment by alrod** [comment]
Latest Service Bus SDK is in the latest extension: https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.ServiceBus/5.3.0
