### ISSUE TITLE
Misleading error messaging when use interpolated connection string

### ISSUE THREAD

**Issue by benbelow** [Azure/azure-functions-servicebus-extension#105]
When setting up a new service bus triggered function, I accidentally used interpolation when setting up my connection string, i.e. 

`%ConnectionStringAppSettingName%` instead of just `ConnectionStringAppSettingName`. 

This leads to the confusingly worded error message : "Connection string <my full connection string> is null or empty" - where the fact it's logging my connection string very much implies it's not null.

From stepping through the code, I worked out that it means "the app setting with the name <my full connection string> evaluates to null or empty - but I think some clarity in this error message that this is the app setting name, rather than the value, could be helpful.

**Comment by sidkri** [comment]
@benbelow could you please provide a sample snippet of config/code where you set %ConnectionStringAppSettingName%. The connection string should not get logged, could you clarify or provide the log line where it got logged (without the actual connection string value). Thanks.
