### ISSUE TITLE
Receiving MessageLockLostException when completing message long before lock timeout in Azure Function

### ISSUE THREAD

**Issue by jdimmerman** [Azure/azure-functions-servicebus-extension#110]
Hey! We have the following configuration:

- A service bus instance with 9 queues, each of which is drained via by an associated Azure function with a batch trigger.
- Each queue is configured identically, with a lock timeout of 5 minutes and the functions all share a host.json with an autoRenewTimeout of 20 minutes (see confirmation in the snippet and screenshot below)
- We have set autoComplete to false and are completing manually. When processing of some item fails, we choose not to complete that particular item out of the batch and let the queue automatically retry it upon lock expiration
- We complete the messages by calling the method MessageReceiver.CompleteAsync(IEnumerable<string> lockTokens) using the passed in MessageReceiver instance from when the function was triggered.

Generally, this works well. However, at high volumes, we are sometimes getting MessageLockLostExceptions when attempting to complete the messages on the queue. The processing generally takes under 30 seconds, most often low single digit seconds. I spotchecked a number of these exceptions and the time from function trigger to the exception upon attempt to complete ranged from 2 seconds to 15 seconds across 10 occurrences.

It's unclear if this is happening at high volumes due to the load being the direct cause or simply the high number of executions raising an already unlikely issue. However, note that we see it most often near the end of a high volume period, indicating that the high volume itself may be the cause.

This seems like a bug with the Service Bus server, though I may be misunderstanding the expected configuration. Can someone please take a look?

host.json:
`
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingExcludedTypes": "Request",
      "samplingSettings": {
        "isEnabled": true
      }
    }
  },
  "extensions": {
    "serviceBus": {
      "prefetchCount": 1000,
      "autoRenewTimeout": "00:20:00",
      "batchOptions": {
        "maxMessageCount": 1000,
        "autoComplete": false
      }
    }
  }
}
`

Queue configuration:
![image](https://user-images.githubusercontent.com/12055704/93393292-435d3a00-f840-11ea-9ca2-92842c742ba1.png)

Thanks!
Jason

**Comment by joeyeng** [comment]
This issue seems to be related: https://github.com/Azure/azure-functions-servicebus-extension/issues/76
