### ISSUE TITLE
Message Processing Order Across Service Bus Queues

### ISSUE THREAD

**Issue by SamNutkinsPM360** [Azure/azure-functions-servicebus-extension#113]
I have a single Azure Function app containing multiple `ServiceBusTrigger` functions, each responding to messages from different queues.  I do some throughput limiting using the `maxConcurrentCalls` and scale limiting (on the Function App itself) to limit load on downstream resources.  Because of this, messages are sometimes waiting in queue for a period of time.  

In this scenario, how does the function host determine which queues' messages to process first?  For example, Queue A receives 10 messages.  The function app begins processing them.  Then Queue B receives 10 messages. Will Queue B's messages only be processed once Queue A's are fully processed? Or is it done in a round robin fashion?

Any insight or documentation references appreciated - thanks in advance.

**Comment by alrod** [comment]
@SamNutkinsPM360, Function host have 2 different listeners for  Queue A and Queue B and the queues will be processed concurrently. So for 2 queues you concurrency will be `maxConcurrentCalls * 2`
