### ISSUE TITLE
Question : how to get the message in dependency injection ?

### ISSUE THREAD

**Issue by jonathanantoine** [Azure/azure-functions-servicebus-extension#115]
Hello,

I would like to initialize some transient services based on the content of the received message. 
Using an http trigger, I can do it using the IHttpContextAccessor. Is there some equivalent (or workaround) regarding service bus trigger ?

Thanks a lot !

**Comment by alrod** [comment]
There is not really an equivalent of IHttpContextAccessor for ServiceBus trigger. You can get metadata directly:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus-trigger?tabs=csharp#message-metadata

What so you want to achieve with the "transient services"?
