### ISSUE TITLE
Function fails to start/process messages with "Can't create session when the connection is closing"

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/azure-functions-servicebus-extension#117]
Function fails to start/process messages with "Can't create session when the connection is closing" and stops working. Since we are running this on Kubernetes we have to manually kill the pod so that it restarts which is a high-prio issue in production.

Relates to https://github.com/Azure/azure-sdk-for-net/issues/13637

**Comment by alrod** [comment]
@tomkerkhove, it looks like the issue was fixed in 5.1.0
https://github.com/Azure/azure-sdk-for-net/issues/13637#issuecomment-732409303
do you experience the issue with 5.1.0?

**Comment by tomkerkhove** [comment]
Hi,

This has been a while since I opened the issue and no longer recall what version it was running nor I can test it - Sorry!
