### ISSUE TITLE
Get MessageReceiver via container

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-functions-servicebus-extension#119]
Is it possible to inject `MessageReceiver` into the function or gain access to it via Functions container?

**Comment by SeanFeldman** [comment]
@soninaren, is this something that could be answered? Thank you.

**Comment by soninaren** [comment]
cc: @sidkri

**Comment by alrod** [comment]
dup:
https://github.com/Azure/azure-functions-servicebus-extension/issues/120
