### ISSUE TITLE
Add binding and tests for IMessageReceiver in ServiceBusTrigger #2218

### ISSUE THREAD

**Issue by StannieV** [Azure/azure-functions-servicebus-extension#124]
As mentioned in [issue 2222](https://github.com/Azure/azure-webjobs-sdk/issues/2222), I'm interested in 'Support interface IMessageReceiver via Dependency Injection'. Please add this feature so unit testing is easier.

**Comment by mneiman** [comment]
+1 I support adding this feature

**Comment by Titismile** [comment]
+1 , we badly need this feature.

**Comment by Griind** [comment]
+1

**Comment by jainaashish** [comment]
+1 I can't believe this is still open after ~2.5 years.

**Comment by StannieV** [comment]
@jainaashish I don't think this will be fixed because, since version 5.0.0 of 'Microsoft.Azure.WebJobs.Extensions.ServiceBus,  the IMessageReceiver of 'Microsoft.Azure.ServiceBus' is replaced by other classes in 'Azure.Messaging.ServiceBus'. Like: 'ServiceBusClient' and 'ServiceBusMessageActions.'

Therefore I'll close this issue.
