### ISSUE TITLE
Azure Service Bus SDK 7 support

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-functions-servicebus-extension#128]
With Azure Service Bus[ SDK 7 GA-ed](https://devblogs.microsoft.com/azure-sdk/november-2020-servicebus-ga), what's the plan for `ServiceBusTrigger`?

**Comment by SeanFeldman** [comment]
@sidkri its not an easy ask but would appreciate so information to be shared about the plans moving forward. Thank you.

**Comment by SeanFeldman** [comment]
Connecting the dots: https://github.com/Azure/azure-sdk-for-net/issues/17563

**Comment by sidkri** [comment]
Will loop in the right contact here.

**Comment by jsquire** [comment]
Hi @SeanFeldman.  The SDK team has started working to update the Service Bus bindings and the first step of migrating them over to the Azure SDK repository is complete.  They're available [here](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus) as a sibling package to the Service Bus client libraries.

The work is being tracked in the Azure SDK repository using the tags `Service Bus` and `Extensions`;  the current set can be found [here](https://github.com/Azure/azure-sdk-for-net/issues?q=is%3Aopen+is%3Aissue+label%3A%22Service+Bus%22+label%3A%22Extensions%22).  Development will be following our usual patterns, which you're familiar with from the help that you provided during the client library development.

Please feel free to open issues for discussion in the SDK repo.

**Comment by alrod** [comment]
already done in https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.ServiceBus/5.3.0
