### ISSUE TITLE
Operation Id is lost from message producer to message consumer

### ISSUE THREAD

**Issue by Anthony-Breneliere** [Azure/azure-functions-servicebus-extension#129]
I have two function apps: **receiver** that send messages in a topic, and **processor** that receive messages from a subscription from that topic.

**Before** migrating **processor** to Azure Function V3, in application Insight, traces from **receiver** and **processor** have the same operation Id.

**After** migrating **processor** to Azure Function V3, a new operation Id is created for each message received by the  **processor** function app.

That is an issue because application insight cannot make the link between the message received in the **receiver** and the message processed in the **processor**. **Requests** sent to application insight by the **processor** have a wrong operation Id.

To migrate  **processor** to Azure Function V3, I had to add the following dependency in the .csproj in order to use ServiceBusTrigger:
```
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="4.1.0" />
```

**Comment by alrod** [comment]
operation-id correlation should work Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.x.
@Anthony-Breneliere, have you checked it?
