### ISSUE TITLE
Set sessionId with `$return` output binding

### ISSUE THREAD

**Issue by pawepaw** [Azure/azure-functions-servicebus-extension#136]
Hi,

I'm currently developing azure function with service bus binding. We want to enable session support on service bus and i'm wondering if it's possible to set SessionId somehow when using `$return`  binding from function.

I've Tried to set `"isSessionsEnabled": true` in function.json binding and explicitly set `SessionId` property in return value but it isn't working. I'm getting exception that SessionId is not set.

```
The SessionId was not set on a message, and it cannot be sent to the entity. Entities that have session support enabled can only receive messages that have the SessionId set to a valid value.```

**Comment by alrod** [comment]
@pawepaw, what language do you use?

**Comment by pawepaw** [comment]
@alrod C#

**Comment by shreyabatra4** [comment]
This will be tracked here: https://github.com/Azure/azure-sdk-for-net/issues/21884
