### ISSUE TITLE
Disabled Autocomplete, MessageReceivePump attempts to Abandon messages

### ISSUE THREAD

**Issue by zamzowd** [Azure/azure-functions-servicebus-extension#142]
Even though I have autocomplete disabled and I deadlettered the message in the function, if I then throw an exception, then in addition to the logged exception I also I get a `MessageLockLostException` logged from `MessageReceivePump.AbandonMessageIfNeeded` attempting to abandon the message I already deadlettered.

So far as I know, throwing an exception is the only way that the function execution is logged as unsuccessful.

If I'm not mistaken, I think the [SessionMessageProcessor](https://github.com/Azure/azure-functions-servicebus-extension/blob/dev/src/Microsoft.Azure.WebJobs.Extensions.ServiceBus/SessionMessageProcessor.cs#L67) on the single dispatch should check for `AutoComplete` before rethrowing similar to [ServiceBusListener](https://github.com/Azure/azure-functions-servicebus-extension/blob/062a555f203b34fc3f0779fc2a85365f643276ae/src/Microsoft.Azure.WebJobs.Extensions.ServiceBus/Listeners/ServiceBusListener.cs#L316) on the batch processing.

**Comment by b10-dslappendel** [comment]
This seems to be the same issue as reported here: https://github.com/Azure/azure-webjobs-sdk/issues/2152 (it has been an issue for more than 2 years now)

**Comment by alrod** [comment]
it's already fixed in latest SB extension https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.ServiceBus/5.3.0
