### ISSUE TITLE
Service Bus Batch Trigger

### ISSUE THREAD

**Issue by BrianVallelunga** [Azure/azure-functions-servicebus-extension#15]
I'd like to start a conversation around supporting batches of messages from an Azure Service Bus. A similar request was made for Storage Queues in https://github.com/Azure/azure-webjobs-sdk/issues/625

Ideally, I'd be able to specify something like:

    public void Handle([ServiceBusBatchTrigger("myqueue", 25)] BrokeredMessage[] messages)
    {
      // Process the batch of messages  
    }

There are a lot of scenarios where batching message processing is far more efficient than working with an individual message. In my specific case, I'm doing database inserts and those could be done much more efficiently in a batch.

I'm going to look into a similar project that supports Storage Queues: https://github.com/ealsur/WebJobs.Extensions.GroupQueueTrigger

Is this something others would be interested in?

**Comment by SeanFeldman** [comment]
@alrod could you please share a link to the documentation (or PR) for this new addition? Thank you.

**Comment by alrod** [comment]
There is not documentation in the moment.
Using:
```
        [FunctionName("Function1")]
        public static void Run([ServiceBusTrigger("myqueue", Connection = "AzureWebJobsServiceBus")]string[] mySbMsg, ILogger log)
        {..}
```
Also you can specify `Message[], byte[][], PocoClass[]` as the input trigger param.

Note `SingletonOptions` defined in `host.json` don't apply to batch processing

PR:
https://github.com/Azure/azure-functions-servicebus-extension/pull/11

**Comment by nzthiago** [comment]
@alrod I *think* when you use ISessionClient (which inherits and expands on IMessageReceiver) it will still be able to ReceiveAsync with a batch for a specific SessionId (gotta call AcceptMessageSessionAsync first to get an IMessageSession). 

I created a simple sample netcoreapp2.2 here: https://github.com/nzthiago/ServiceBusBatchReceiveWithSessions

As you can see it sends 10 messages to 2 sessions ("1", and "2"). Then it tries to read from only session "1" in batches of 5 and it's successful: 
![image](https://user-images.githubusercontent.com/1563288/63902326-ed5fef00-c9bd-11e9-9877-fdbd10236c11.png)

**Comment by rasavant-ms** [comment]
Would be nice to have the metadata properties available for the earlier versions supported as valid parameter Types in the new package version - Microsoft.Azure.WebJobs.Extensions.ServiceBus 3.1.0-beta4-batch

I got an error while executing a function with the 'EnqueuedTimeUtc' property - 
`
[8/29/2019 3:39:35 AM] Function1: Microsoft.Azure.WebJobs.Host: Error indexing method 'Function1'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'enqueuedTimeUtc' to type DateTime. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
`

**Comment by JoeyRobles** [comment]
@alrod Microsoft.Azure.WebJobs.Extensions.ServiceBus was updated to 3.1.0 a couple of days ago
Was batching in Service Bus Queue Triggers included? Thanks in advanced.

**Comment by remartens** [comment]
@JoeyRobles it looks like it doesn't. It looks like the 3.1.0 is based on the 3.1.0-beta4 and not on the 3.1.0-beta4-batch. :-(

**Comment by alrod** [comment]
> @alrod I _think_ when you use ISessionClient (which inherits and expands on IMessageReceiver) it will still be able to ReceiveAsync with a batch for a specific SessionId (gotta call AcceptMessageSessionAsync first to get an IMessageSession).
> 
> I created a simple sample netcoreapp2.2 here: https://github.com/nzthiago/ServiceBusBatchReceiveWithSessions
> 
> As you can see it sends 10 messages to 2 sessions ("1", and "2"). Then it tries to read from only session "1" in batches of 5 and it's successful:
> ![image](https://user-images.githubusercontent.com/1563288/63902326-ed5fef00-c9bd-11e9-9877-fdbd10236c11.png)

@nzarrari, you are right. We can add session support for batching using `MessageSession.ReceiveBatch`. I'll take a look how to add this.

**Comment by alrod** [comment]
> @alrod Microsoft.Azure.WebJobs.Extensions.ServiceBus was updated to 3.1.0 a couple of days ago
> Was batching in Service Bus Queue Triggers included? Thanks in advanced.

@JoeyRobles, 3.1.0 does not include batching.

**Comment by nzthiago** [comment]
Thanks @alrod! Adding that batching support for session receives would improve the perf considerably I suspect.

**Comment by alrod** [comment]
> VERIFIED THAT THIS WORKS WITH THE BETA PACKAGE. IGNORE MESSAGE!
> 
> Would be nice to have the metadata properties available for the earlier versions supported as valid parameter Types in the new package version - Microsoft.Azure.WebJobs.Extensions.ServiceBus 3.1.0-beta4-batch
> 
> I got an error while executing a function with the 'EnqueuedTimeUtc' property -
> `[8/29/2019 3:39:35 AM] Function1: Microsoft.Azure.WebJobs.Host: Error indexing method 'Function1'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'enqueuedTimeUtc' to type DateTime. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).`

@rasavant-ms, you can do it using `DateTime[] enqueuedTimeUtcArray`:
```
        public static async Task Run([ServiceBusTrigger("queue1")]Message[] messages, DateTime[] enqueuedTimeUtcArray, ILogger log)
        {
        }
```

**Comment by kwasak** [comment]
> > VERIFIED THAT THIS WORKS WITH THE BETA PACKAGE. IGNORE MESSAGE!
> > Would be nice to have the metadata properties available for the earlier versions supported as valid parameter Types in the new package version - Microsoft.Azure.WebJobs.Extensions.ServiceBus 3.1.0-beta4-batch
> > I got an error while executing a function with the 'EnqueuedTimeUtc' property -
> > `[8/29/2019 3:39:35 AM] Function1: Microsoft.Azure.WebJobs.Host: Error indexing method 'Function1'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'enqueuedTimeUtc' to type DateTime. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).`
> 
> @rasavant-ms, you can do it using `DateTime[] enqueuedTimeUtcArray`:
> 
> ```
>         public static async Task Run([ServiceBusTrigger("queue1")]Message[] messages, DateTime[] enqueuedTimeUtcArray, ILogger log)
>         {
>         }
> ```

I tried implementing this pattern with Microsoft.Azure.WebJobs.Extensions.ServiceBus 3.1.0-beta4-batch installed and I keep getting this exception:

System.InvalidOperationException: Exception binding parameter 'messages' ---> System.InvalidOperationException: Binding parameters to complex objects (such as 'Message[]') uses Json.NET serialization or XML object serialization. 
 1. If ContentType is 'application/json' deserialize as JSON
 2. If ContentType is not 'application/json' attempt to deserialize using Message.GetBody, which will handle cases like XML object serialization
 3. If this deserialization fails, do a final attempt at JSON deserialization to catch cases where the content type might be incorrect
The JSON parser failed: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'Microsoft.Azure.ServiceBus.Message[]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'id', line 1, position 6.

**Comment by jeffhollan** [comment]
I'm hitting this latest one on `Microsoft.Azure.WebJobs.Extensions.ServiceBus` version `3.2.0`.

@alrod any thoughts here?  Sounds like it may have worked on earlier builds

```csharp
public static void Run(
            [ServiceBusTrigger("queue", Connection = "ServiceBusConnection", IsSessionsEnabled = true)] Message[] myQueueItems, 
            ILogger log)
        { . .. }
```

And it spits out:

>Message processing error (...)
System.Private.CoreLib: Exception while executing function: BatchQueueTrigger. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'myQueueItems'. Microsoft.Azure.WebJobs.ServiceBus: Binding parameters to complex objects (such as 'Message[]') uses Json.NET serialization or XML object serialization. 
   1. If ContentType is 'application/json' deserialize as JSON
   2. If ContentType is not 'application/json' attempt to deserialize using Message.GetBody, which will handle cases like XML object serialization
   3. If this deserialization fails, do a final attempt at JSON deserialization to catch cases where the content type might be incorrect
The JSON parser failed: Unexpected character encountered while parsing value: H. Path '', line 0, position 0.

**Comment by jeffhollan** [comment]
Sorry my bad - @alrod helped me - the current preview functionality of batch receive is in this NuGet package version.  we're working on a plan to bump it to a non-beta version:

https://www.myget.org/feed/azure-appservice/package/nuget/Microsoft.Azure.WebJobs.Extensions.ServiceBus/3.1.0-beta4-batch

**Comment by jeffhollan** [comment]
// @fabiocav per our chat I flagged this as a P1 to hopefully show up in queries into coming plans

**Comment by fabiocav** [comment]
Just had a chat with @alrod and there's a PR out that is a bit stale and needs to be updated. I think at this point, we're comfortable targeting next sprint (63) for completion.

**Comment by jeffhollan** [comment]
Awesome. And assuming that includes both session and non session batch support. Thanks all

**Comment by nzthiago** [comment]
Great to see this progressing to include batches in session and non-sessions. For session enabled I would be interested in knowing or have documented:
* What will be decision point for closing of a session (i.e., releasing a session lock)? I assume time based after no more messages are in the session? And if so, how long is that time?
* Confirmation that messages received in each batch will be in order in the array?

**Comment by SibeeshVenu** [comment]
Is this working with the version **3.2.0** ? I am still getting the error as below. Any updates?

> [11/11/2019 12:15:56 PM] System.Private.CoreLib: Exception while executing function: InformationSubscription. Microsoft.Azure.WebJobs.Host: One or more errors occurred. (Exception binding parameter 'mySbMsg') (Exception binding parameter 'messageReceiver') (Exception binding parameter 'lockToken'). Exception binding parameter 'mySbMsg'. Microsoft.Azure.WebJobs.ServiceBus: Binding parameters to complex objects (such as 'Message[]') uses Json.NET serialization or XML object serialization.
> [11/11/2019 12:15:56 PM]  3. If this deserialization fails, do a final attempt at JSON deserialization to catch cases where the content type might be incorrect
> [11/11/2019 12:15:56 PM]  3. If this deserialization fails, do a final attempt at JSON deserialization to catch cases where the content type might be incorrect
> [11/11/2019 12:15:56 PM] The JSON parser failed: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'Microsoft.Azure.ServiceBus.Message[]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.

**Comment by alrod** [comment]
Batch support will be released in the first week of next year. You can try the exact package in staging:
https://myget.org/feed/azure-appservice-staging/package/nuget/Microsoft.Azure.WebJobs.Extensions.ServiceBus/4.1.0

**Comment by alrod** [comment]
Released:
https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.ServiceBus/4.1.0

**Comment by elksson** [comment]
@alrod is there a configuration to specify the max batch size?

**Comment by kwasak** [comment]
@alrod Thanks for releasing batching support, it works great.
Noticed, messages received in batches are not correlated end-to-end with application Insights. This isn't an issue when binding to a signal element. 

I really liked end-to-end correlation with Application insights, as it would show 'Time Spent in Queue' as well as the original request!. Is there any plans in enabling this feature for batching?

**Comment by BrianVallelunga** [comment]
Thanks for seeing this through. It's a very useful feature!

**Comment by shaduk** [comment]
Thanks for adding support for batch!. Is there any official documentation I can refer to?. My main concern is about what happens when an exception occurs for one message in the batch. Will all of them fail and be moved to Deadletter Queue?

**Comment by batizar** [comment]
@alrod  How can we specify the batch size for trigger? thanks.

**Comment by batizar** [comment]
Also how the batch size would work in relation to prefetch count? thanks.

**Comment by RobertPinson** [comment]
@alrod Does the Service Bus trigger batching work for node.js functions?

**Comment by alrod** [comment]
@RobertPinson  yes, it works. you need to add `"cardinality": "many"` in `function.json` 
https://github.com/Azure/azure-functions-servicebus-extension/issues/65

**Comment by alrod** [comment]
@batizar,
you can specify max batch size using ["MaxMessageCount"](https://github.com/Azure/azure-functions-servicebus-extension/blob/dev/test/Microsoft.Azure.WebJobs.Extensions.ServiceBus.Tests/ServiceBusEndToEndTests.cs#L539).
Default value is [1000](https://github.com/Azure/azure-functions-servicebus-extension/blob/dev/src/Microsoft.Azure.WebJobs.Extensions.ServiceBus/Config/ServiceBusOptions.cs#L37)
`MaxMessageCount` is used in `ReceiveAsync` method:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.core.messagereceiver.receiveasync?view=azure-dotnet#Microsoft_Azure_ServiceBus_Core_MessageReceiver_ReceiveAsync_System_Int32_System_TimeSpan_

Prefetching vs batching:
https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-performance-improvements?tabs=net-standard-sdk#prefetching-and-receivebatch

**Comment by RobertPinson** [comment]
> @batizar,
> you can specify max batch size using ["MaxMessageCount"](https://github.com/Azure/azure-functions-servicebus-extension/blob/dev/test/Microsoft.Azure.WebJobs.Extensions.ServiceBus.Tests/ServiceBusEndToEndTests.cs#L539).
> Default value is [1000](https://github.com/Azure/azure-functions-servicebus-extension/blob/dev/src/Microsoft.Azure.WebJobs.Extensions.ServiceBus/Config/ServiceBusOptions.cs#L37)
> `MaxMessageCount` is used in `ReceiveAsync` method:
> https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.core.messagereceiver.receiveasync?view=azure-dotnet#Microsoft_Azure_ServiceBus_Core_MessageReceiver_ReceiveAsync_System_Int32_System_TimeSpan_
> 
> Prefetching vs batching:
> https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-performance-improvements?tabs=net-standard-sdk#prefetching-and-receivebatch

thanks @alrod the cardinality: many worked in my node function, can you set maxMessageCount in a node function?

**Comment by alrod** [comment]
@RobertPinson, @batizar 
This is not documented yet. You need to use[ host.json](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus-output?tabs=csharp#host-json). 

Example:
```
"ServiceBusOptions" : {
    "BatchOptions": {
        "MaxMessageCount": 1000,
        "OperationTimeout": "00:01:00"
        "AutoComplete": "true"
    }
}
```

**Comment by jeffhollan** [comment]
Created a task to track this (internal doc tracking site with our team) https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1778524 

@alrod other piece here would be what the `function.json` would look like for non-C# when using batch.  Does this support `cardinality: many` or is that not needed? In short what would my JavaScript function look like that receives a batch instead of a single message?

**Comment by shaeney** [comment]
Assuming you have Batching via the array of Messages, as per:

`            [ServiceBusTrigger("%ActivitiesSource%",
                "%ActivitiesSourceSubscription%",
                Connection = "ActivitiesConnectionString"], 
                Message[] messages,
                MessageReceiver messageReceiver,
                ILogger log)
`

Assuming AutoComplete is off, an unhandled exception is thrown "Operation is not valid due to the current state of the object." when using the MessageReceiver to Complete or DeadLetter the message.

`messageReceiver.CompleteAsync(message.SystemProperties.LockToken);`

If you remove batching, by removing the array, the same operations no longer generate the exception?

Does batching, via the array, somehow prevent interact with the MessageReceiver to throw the exception?

**Comment by batizar** [comment]
> @RobertPinson, @batizar
> This is not documented yet. You need to use[ host.json](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus-output?tabs=csharp#host-json).
> 
> Example:
> 
> ```
> "ServiceBusOptions" : {
>     "BatchOptions": {
>         "MaxMessageCount": 1000,
>         "OperationTimeout": "00:01:00"
>         "AutoComplete": "true"
>     }
> }
> ```

@alrod thanks for you reply, how is `AutoComplete` setting there is different than what we set in `MessageHandlerOptions` in WebJobs appSettings like this? does that mean that the whole batch gets completed as one or each messages can be completed when its processing is finished?

```  
"AzureWebJobs": {
    "Extensions": {
      "ServiceBus": {
        "PrefetchCount": 50,
        "MessageHandlerOptions": {
          "AutoComplete": false,
          "MaxConcurrentCalls": 16,
          "MaxAutoRenewDuration": "00:05:00"
        }
      }
    }
  }
```

**Comment by shaeney** [comment]
I have a Function with a ServiceBusTrigger, such as below
` 
public  Task SingleMessage(
            [ServiceBusTrigger("%ActivitiesSource%",
                "%ActivitiesSourceSubscription%",
                Connection = "ActivitiesConnectionString")]
                Message message,
                ILogger log)
`
This generates an exception:

Microsoft.Azure.WebJobs.Script.WebHost: Scope disposed{no name} is disposed and scoped instances are disposed and no longer available.

However, if I simply swap "Message message" to "string message", it works?

**Comment by tripodsan** [comment]
> thanks @alrod the cardinality: many worked in my node function, can you set maxMessageCount in a node function?

Hi @RobertPinson, when I try this, I get an error:

> Binding parameters to complex objects (such as 'Object[]') uses Json.NET serialization or XML object serialization. 1. If ContentType is 'application/json' deserialize as JSON 2. If ContentType is not 'application/json' attempt to deserialize using Message.GetBody, which will handle cases like XML object serialization .....

similar to this: https://github.com/Azure/azure-functions-templates/issues/905

but I'm not able to solve this...

**Comment by RobertPinson** [comment]
> > thanks @alrod the cardinality: many worked in my node function, can you set maxMessageCount in a node function?
> 
> Hi @RobertPinson, when I try this, I get an error:
> 
> > Binding parameters to complex objects (such as 'Object[]') uses Json.NET serialization or XML object serialization. 1. If ContentType is 'application/json' deserialize as JSON 2. If ContentType is not 'application/json' attempt to deserialize using Message.GetBody, which will handle cases like XML object serialization .....
> 
> similar to this: [Azure/azure-functions-templates#905](https://github.com/Azure/azure-functions-templates/issues/905)
> 
> ~but I'm not able to solve this...~
> 
> Nevermind, I found my problem, I needed to ensure I get the 2.x extensions:
> 
> ```
>   "extensionBundle": {
>     "id": "Microsoft.Azure.Functions.ExtensionBundle",
>     "version": "[2.*, 3.0.0)"
>   }
> ```
> 
> However, the batching still doesn't work....

Hi @tripodsan the Service Bus batch read feature is in the latest version of the Microsoft.Azure.WebJobs.Extensions.ServiceBus 4.2.0 which is not in the extension bundle. the version of ther service bus extension in the latest bundle is  3.2.0.

To explicitly install the extensions you need to remove the `extensionBundle` section from host.js and run func extensions install

instructions here https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-register

**Comment by nicklasjepsen** [comment]
Really appreciate the support for a batch trigger, however, I can't find it documented anywhere. Is there any official documentation of this functionality?

**Comment by jashuRc** [comment]
> Assuming you have Batching via the array of Messages, as per:
> 
> ` [ServiceBusTrigger("%ActivitiesSource%", "%ActivitiesSourceSubscription%", Connection = "ActivitiesConnectionString"], Message[] messages, MessageReceiver messageReceiver, ILogger log)`
> 
> Assuming AutoComplete is off, an unhandled exception is thrown "Operation is not valid due to the current state of the object." when using the MessageReceiver to Complete or DeadLetter the message.
> 
> `messageReceiver.CompleteAsync(message.SystemProperties.LockToken);`
> 
> If you remove batching, by removing the array, the same operations no longer generate the exception?
> 
> Does batching, via the array, somehow prevent interact with the MessageReceiver to throw the exception?





https://github.com/Azure/azure-sdk-for-net/blob/Microsoft.Azure.WebJobs.Extensions.ServiceBus_5.0.0-beta.2/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/README.md#message-settlement

**Comment by jashuRc** [comment]
> Really appreciate the support for a batch trigger, however, I can't find it documented anywhere. Is there any official documentation of this functionality?

Here: https://github.com/Azure/azure-sdk-for-net/blob/Microsoft.Azure.WebJobs.Extensions.ServiceBus_5.0.0-beta.2/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/README.md#azure-webjobs-service-bus-client-library-for-net

**Comment by nzthiago** [comment]
I would recommend that to be in the official docs on https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus for better discoverability given @nicklasjepsen couldn't find it.

**Comment by jothyb** [comment]
@alrod Can we use service bus batching in java?Should we add anything in the @ServiceBusQueueTrigger annotation to enable this

**Comment by nzthiago** [comment]
@jothyb it doesn't seem like there's documentation for the batch trigger in Java yet; but it's certainly possible, with the Cardinality set to MANY and an array of string in the trigger declaration, see here for an example: https://github.com/Azure/azure-functions-java-worker/blob/976635d81a31f2464f8b5ca1925d91b6e1b139a2/endtoendtests/src/main/java/com/microsoft/azure/functions/endtoend/ServiceBusQueueTriggerTests.java#L24

**Comment by jothyb** [comment]
Thanks @nzthiago for the response.The extension bundle [2.*, 3.0.0) uses version 4.2.0 of service bus extension,so can we use the extension bundle to enable batching @alrod @nzthiago

**Comment by jothyb** [comment]
@nzthiago Thank you for the response .I was able to receive batch messages,but now the problem is I need to get the message properties(custom properties) which is set as part of each message.For single message we achieved it using bindingName,but for batch is there a way to get it in java @alrod

**Comment by nzthiago** [comment]
@jothyb yes you'll need to update the extension bundle to v2, it seems the current VS Code template still points to v1.

I did some digging, it seems that the User Properties [are exposed by the Service Bus extension](https://github.com/Azure/azure-functions-servicebus-extension/blob/32f8df8a62c38cb5ae4333875d73d60f981045a3/src/Microsoft.Azure.WebJobs.Extensions.ServiceBus/Triggers/ServiceBusTriggerBindingStrategy.cs#L107), so I played with it a little and was able to get the user properties by using @BindingName("UserPropertiesArray"). Here's my example:
```java
package com.function;
import java.util.*;
import com.microsoft.azure.functions.annotation.*;
import com.microsoft.azure.functions.*;

public class Sbjavatesttempfunc {
    @FunctionName("Sbjavatesttempfunc")
    public void Sbjavatesttempfunc(
            @ServiceBusQueueTrigger(name = "messages", queueName = "sbjavatesttempqueue", connection = "ServiceBusConnString", 
                                    cardinality = Cardinality.MANY, dataType = "string") List<String> messages,
            @BindingName("UserPropertiesArray") List<String> userPropertiesArray,
            final ExecutionContext context) {
        context.getLogger().info("Java Service Bus trigger processed a request. Total message count:" + messages.size());

        for(int i = 0; i < messages.size(); i++){
            context.getLogger().info("Message number : " + i);
            context.getLogger().info(messages.get(i));
            context.getLogger().info("User properties for message: " + i);
            context.getLogger().info(userPropertiesArray.get(i));
        }
    }
}
``` 

When it reads a batch of messages, it will print out as follows:
![image](https://user-images.githubusercontent.com/1563288/119567979-d6e8f200-bd61-11eb-9c8a-2abad80e7e5c.png)

You can probably convert the userPropertiesArray to a Map, but I kept it simple, let me know if this works for you.

**Comment by jothyb** [comment]
Thank you @nzthiago ,it worked 👍 .

**Comment by Nehmiabm** [comment]
Hello there,

Is batching currently supported only for InProcess funcitons? I tried the host batch configurations, for Isolated function, with string[] ServiceBusTrigger param but it's not working. Any update if this is supported for Isolated functions?

**Comment by anirudhgarg** [comment]
> @nzthiago Thank you for the response .I was able to receive batch messages,but now the problem is I need to get the message properties(custom properties) which is set as part of each message.For single message we achieved it using bindingName,but for batch is there a way to get it in java @alrod

Here are some examples: https://github.com/Azure-Samples/azure-functions-samples-java/blob/master/src/main/java/com/functions/ServiceBusQueueTriggerFunction.java#L26

**Comment by kshyju** [comment]
@Nehmiabm Batching of messages works as expected, for service bus trigger in dotnet isolated model. See working sample code & host JSON [here](https://github.com/Azure/azure-functions-dotnet-worker/issues/906#issuecomment-1136294241). Let us know if you still have trouble with this.

**Comment by Niladri24dutta** [comment]
@nzthiago I am trying to use batch messages in service bus trigger for Azure functions . I am using Azure functions python library . As per the below URL I can see that the batching was enabled on python version from 1.5.0 onwards 
https://github.com/Azure/azure-functions-python-library/pull/73 
https://github.com/Azure/azure-functions-python-library/releases/tag/1.5.0
I am using the below URL as a reference for extensions under bundle version 3x.
https://github.com/Azure/azure-functions-extension-bundles/blob/4f5934a18989353e36d771d0a964f14e6cd17ac3/src/Microsoft.Azure.Functions.ExtensionBundle/extensions.json
But when I am trying to use batch messages in my function app , I am getting JSON .NET deserialization error in the binding parameter. Here are the details -

Azure function version : 4
Azure function python package version : 1.8.0
Extension bundle version : 3x

**host.json** 
```
{

  "version": "2.0",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[3.3.0, 4.0.0)"
  },
  "extensions":   {
    "serviceBus": {
      "prefetchCount": 20,
      "messageHandlerOptions": {
        "autoComplete": true,
        "maxConcurrentCalls": 1,
        "maxAutoRenewDuration": "00:05:00"
      }
    }
  }
}
```

**function.json**

```
{
  "scriptFile": "__init__.py",
  "bindings": [
    {
      "name": "msg",
      "type": "serviceBusTrigger",
      "direction": "in",
      "cardinality": "many",
      "queueName": "queue-many",
      "connection": "SERVICE_BUS_CONNECTION"
    }
  ]
}

```
**sample code in function app**

```
import logging

import azure.functions as func
from typing import List


def main(msg: List[func.ServiceBusMessage]):
    message_length = len(msg)
    if message_length > 1:
        logging.warn('Handling multiple requests')
```
am I missing anything here ?
