### ISSUE TITLE
Support for runtime 1.x

### ISSUE THREAD

**Issue by unruledboy** [Azure/azure-functions-servicebus-extension#159]
Hi,

We have an existing function app that uses runtime 1.x, and it has dependency on 3rd party libraries that uses .NET Framework 4.x so that I could not properly use runtime 2.x.

Now that we need to add support to return a service buss message as the output of a function app, we could not install Microsoft.Azure.WebJobs.Extensions.ServiceBus because it is minimal 3.0 and it does not work with Microsoft.Azure.WebJobs 2.x that the runtime 1.x uses.

Can you please advise what and how exactly we can use for runtime 1.x?

Thanks.

**Comment by alrod** [comment]
for 1.x runtime you can use https://www.nuget.org/packages/Microsoft.Azure.WebJobs.ServiceBus
for > 2.x please use https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.ServiceBus
