### ISSUE TITLE
ServiceBusTrigger Fires Again Immediately After Exception in User Code

### ISSUE THREAD

**Issue by phil000** [Azure/azure-functions-servicebus-extension#161]
We are using ServiceBusTrigger in Azure Functions.

"FUNCTIONS_WORKER_RUNTIME": "dotnet-isolated"

Microsoft.Azure.Functions.Worker.Extensions.ServiceBus 4.2.1
Microsoft.Azure.Functions.Worker.Sdk 1.0.2
Microsoft.Azure.Functions.Worker 1.1.0

When an exception occurs in user code the same message is tried again without any delay. I would have expected that the lock timeout would have been allowed to expire first. Otherwise we get {max dequeue count} errors occurring within about 5 seconds and the message moves to the dead letter queue.

**Comment by phil000** [comment]
Just some debug.writeline to show message id, dequeue count, and time it is being processed after an exception occurs and is thrown out of user code:

13/05/2021 4:04:03 pm - Processing Message Id: 679b17da-6d1b-405f-9262-ec8535cb22ea, Dequeue Count: 1
13/05/2021 4:04:05 pm - Exception in user code SqlException. Will be thrown out to runtime.

13/05/2021 4:04:06 pm - Processing Message Id: 679b17da-6d1b-405f-9262-ec8535cb22ea, Dequeue Count: 2
13/05/2021 4:04:06 pm - Exception in user code SqlException. Will be thrown out to runtime.

13/05/2021 4:04:06 pm - Processing Message Id: 679b17da-6d1b-405f-9262-ec8535cb22ea, Dequeue Count: 3
13/05/2021 4:04:06 pm - Exception in user code SqlException. Will be thrown out to runtime.

13/05/2021 4:04:07 pm - Processing Message Id: 679b17da-6d1b-405f-9262-ec8535cb22ea, Dequeue Count: 4
13/05/2021 4:04:07 pm - Exception in user code SqlException. Will be thrown out to runtime.

13/05/2021 4:04:07 pm - Processing Message Id: 679b17da-6d1b-405f-9262-ec8535cb22ea, Dequeue Count: 5
13/05/2021 4:04:08 pm - Exception in user code SqlException. Will be thrown out to runtime.

13/05/2021 4:04:08 pm - Processing Message Id: 679b17da-6d1b-405f-9262-ec8535cb22ea, Dequeue Count: 6
13/05/2021 4:04:08 pm - Exception in user code SqlException. Will be thrown out to runtime.

13/05/2021 4:04:08 pm - Processing Message Id: 679b17da-6d1b-405f-9262-ec8535cb22ea, Dequeue Count: 7
13/05/2021 4:04:08 pm - Exception in user code SqlException. Will be thrown out to runtime.

**Comment by phil000** [comment]
Any idea how we can get the reties after an exception to occur AFTER the message lock timeout we have configured has expired, to give us time to solve any issue? 
Really no point having all 12 dequeues of the message happing in 5 seconds, we already use transient fault handling so the dequeues need to be far enough apart to deal with longer more persistent problems. 
With Azure Storage Queues this all works properly. After an exception you'll see the message again after the visibility timeout expires, so in our case 30 minutes later.

**Comment by phil000** [comment]
29 days?

**Comment by austinkispotta-gep** [comment]
I have the same issue. Is there any inbuild solution to this?
Or any alternatives?

**Comment by phil000** [comment]
@Bubba95x I've had a look at a few things and it's not looking good.

The FixedDelayRetry attribute applied directly to service bus triggered functions does nothing. Seems completely ignored both in terms of retry count and delay.

When using the 'retry' settings in host.json the retry count _is_ used for 'local' retries, but the delay is completely ignored.
Aka, with a maxRetryCount of 1 you get this pattern:
1. message delivered with service bus 'deliveryCount' = *1*
2. message delivered again without any delay and with service bus 'deliveryCount' = *1*
3. message delivered again without any delay and with service bus 'deliveryCount' = *2*
4. message delivered again without any delay and with service bus 'deliveryCount' = *2*

e.g
29/08/2021 10:59:45 am - Message received. DeliveryCount: 1, MessageId: ba33a8e9-cf4b-4a51-b7e7-adf343ecf0b5
29/08/2021 10:59:46 am - Message received. DeliveryCount: 1, MessageId: ba33a8e9-cf4b-4a51-b7e7-adf343ecf0b5
29/08/2021 10:59:47 am - Message received. DeliveryCount: 2, MessageId: ba33a8e9-cf4b-4a51-b7e7-adf343ecf0b5
29/08/2021 10:59:48 am - Message received. DeliveryCount: 2, MessageId: ba33a8e9-cf4b-4a51-b7e7-adf343ecf0b5

**Comment by phil000** [comment]
Been 3 months and not a single comment from Microsoft.

**Comment by phil000** [comment]
A few things have been updated in the last 3 months, still no improvement.

Microsoft.Azure.Functions.Worker.Extensions.ServiceBus 4.2.1
Microsoft.Azure.Functions.Worker.Sdk 1.0.4
Microsoft.Azure.Functions.Worker 1.5.1
