### ISSUE TITLE
Logging function name on ServiceBus exception

### ISSUE THREAD

**Issue by alrod** [Azure/azure-functions-servicebus-extension#162]
This will allow to sort ServiceBus exceptions by function name in ServiceBus detector.

**Comment by cachai2** [comment]
Done in track1. Need to port to track2

**Comment by cachai2** [comment]
@alrod to check if this is done in track2

**Comment by alrod** [comment]
This is not done in track2
https://github.com/Azure/azure-functions-servicebus-extension/commit/cd7528ae4aab8ba90531a90e33e41b4e46cc4801
