### ISSUE TITLE
Emit ServiceBus SDK logs to help diagnose issues

### ISSUE THREAD

**Issue by sidkri** [Azure/azure-functions-servicebus-extension#168]
We have come across an infrequent issue where the service bus client (either the extension of the Service Bus SDK) is acquiring and then abandoning messages in rapid succession (within milliseconds) with no errors emitted in the logs.  The Service Bus Extension does register an exception handler with the Service Bus SDK and logs when invoked but these logs do not show up when the issue occurs so we need to see if there is an exception in the Service Bus SDK layer that does not invoke the handler.  This can be done by creating an EventListener class listening to Microsoft.Azure.ServiceBus.MessagingEventSource:

[EventListener Class (System.Diagnostics.Tracing) | Microsoft Docs](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.tracing.eventlistener?view=net-5.0)

**Comment by cachai2** [comment]
https://github.com/Azure/azure-functions-servicebus-extension/pull/170

**Comment by cachai2** [comment]
This is supported in the 5.x+ version of the Service Bus sdks and is enabled by default. For info on using this version, refer here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus#service-bus-extension-5x-and-higher.

**Comment by alrod** [comment]
This is done in track2 (5.x). Also you can use filtering:
https://github.com/Azure/azure-sdk-for-net/issues/25865#issuecomment-992067772
