### ISSUE TITLE
Updating from 4.3.0 to 5.1.0 of Microsoft.Azure.WebJobs.Extensions.ServiceBus

### ISSUE THREAD

**Issue by twiga2013** [Azure/azure-functions-servicebus-extension#173]
Hi
When I update Microsoft.Azure.WebJobs.Extensions.ServiceBus from 4.3.0 to 5.1.0. My existing Azure Function Service Bus Trigger signature does not work anymore.  I am upgrading from Azure Function .NET Core 3.1 to .NET 6.0

<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.5.1" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="5.1.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.0.1" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>

`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.5.1" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="5.1.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.0.1" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>`
 ```
using System;
using System.Threading.Tasks;
using Microsoft.Azure.ServiceBus;
using Microsoft.Azure.ServiceBus.Core;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Host;
using Microsoft.Extensions.Logging;

 public async Task Run([ServiceBusTrigger("subprocess", Connection = "atsb", AutoComplete = false)] Message message,
                               MessageReceiver messageReceiver,
                               [ServiceBus("subprocess", Connection = "atsb")] MessageSender sender,
                               ILogger log)

```
I get 

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'ServiceBus' does not exist in the namespace 'Microsoft.Azure' (are you missing an assembly reference?)	FunctionApp14	C:\Users\XXXXX\source\repos\FunctionApp14\FunctionApp14\Function3.cs	3	Active

**Comment by cachai2** [comment]
Can you double check your app settings and connection strings for your Service Bus connection?
