### ISSUE TITLE
[QUERY] Mark this repo as obsolete and point to the correct repo

### ISSUE THREAD

**Issue by havarnov** [Azure/azure-functions-servicebus-extension#189]
I was looking into this repo and couldn't figure out why I couldn't find version 5.x.

Maybe there should be a section in the README explaining that this code is maintained in the https://github.com/Azure/azure-sdk-for-net repo going forward?

**Comment by fowl2** [comment]
The full path: https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus

**Comment by fowl2** [comment]
It'd be really great for some guidance about what do to about issues.

eg. https://github.com/Azure/azure-functions-servicebus-extension/issues/76 and https://github.com/Azure/azure-functions-servicebus-extension/issues/110 are pretty serious and still seem to affect v5. Should they be duplicated in [Azure/azure-sdk-for-net](https://github.com/Azure/azure-sdk-for-net)?
