### ISSUE TITLE
ServiceBusTriggers generate absurd number of requests on ServiceBus

### ISSUE THREAD

**Issue by mrwatts** [Azure/azure-functions-servicebus-extension#19]
When a function with a ServiceBusTrigger is published, it will generate hundreds of requests on the ServiceBus per minute.

#### Expected behavior

The ServiceBusListener uses MessageReceiver.RegisterMessageHandler. The MessageReceiver has a default ReceiveTimeout of 1 minute, so under usual circumstances listening on a queue or topic subscription generates one request per minute if there aren't any messages to process. This can be verified in a very simple console app (see code below). So this is what would be expected of the ServiceBusListener too (times the number of hosts running obviously).

[This link ](https://social.msdn.microsoft.com/Forums/en-US/86a07793-6dcf-4e9f-8448-4eab611b3836/how-to-receive-message-from-azure-service-bus-queue-without-polling-a-queue?forum=WAVirtualMachinesVirtualNetwork)provides some additional info on how MessageReceiver.RegisterMessageHandler is intended to work.

#### Actual behavior

A single ServiceBusTrigger function on a single webhost will actually generate around a hundred requests per minute. So obviously something is going horribly wrong. This is a painful issue as customers are actually being billed for these requests.

#### Known workarounds

There aren't any.

#### Related information 
Below is a simple class that, when used in a Console App, will receive messages posted on a topic instantly, while only generating a single request per minute if there aren't any messages to process:

```
	class MessageProcessor
	{
		private const string connectionString = @"Endpoint=sb://<myservicebus>.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=<key>";
		MessageReceiver receiver;

		internal void Start()
		{
			var options = new MessageHandlerOptions(HandleException);

			var path = EntityNameHelper.FormatSubscriptionPath("test", "tester");

			receiver = new MessageReceiver(connectionString, path);
			receiver.RegisterMessageHandler(ProcessMessageAsync, options);
		}

		internal void Stop()
		{
			receiver.CloseAsync().GetAwaiter().GetResult();
		}

		private async Task HandleException(ExceptionReceivedEventArgs arg)
		{
			await Task.Delay(100);
		}

		private async Task ProcessMessageAsync(Message message, CancellationToken cancellationToken)
		{
			Console.WriteLine("Message received");
			await Task.Delay(100);
		}
	}
```

**Comment by marxxxx** [comment]
only known workaround is to use Eventgrid in the middle and get your function triggered by Eventgrid then.but this way you might lose ordering and transactional guarantees ServiceBus offers.

**Comment by Sparkeroo96** [comment]
@alrod Is there any up date to this yet? How much is the cost likely to be?

**Comment by SebastianAchatz** [comment]
Any updates on this? Is this still an issue? We are currently evaluating options for a customer to create a new product based on serverless tech stack with Azure Functions and Service Bus (Sessions and Ordering) and this issue would be an **absolute** showstopper. (AWS with SQS is the working alternative) // cc: @paulbatum @jeffhollan

**Comment by macux** [comment]
If there are 100 requests per minute, we have roughly 100 x 60 x 730 per month ~= 4.38M requests. Let's assume you have 20 functions with SB triggers that amounts to ~87.6M requests per month. Assuming a standard tier ASB you get 13M ops free so with current pricing this would cost just over £50 per month according to the calculator (no relays or anything fancy).

In other words base cost with no actual work going on would be £50 for ASB itself, plus whatever you pay for your functions. Haven't bothered to calc the cost of the functions as worst case you'd go for 1+ Linux app service plan(s) from £50 or better a Premium v3 reservation (which are still refundable within the reserve period).

Also not including actual workload costs and scaling out, but this would probably be trivial compared to the polling, and if it's not you can probably more than afford the above!

Am I missing something here? Or do these figures look correct??

**Comment by jameswoodley** [comment]
We are seeing this now, ASB seems to just have thousands of requests for no work happening (nothing in queue yet) - this can't be a feasible long term solution surely? 

The workaround using EventGrid, does this work with Standard ASB?

**Comment by tgjzd** [comment]
Considering the price of ASB premium(standard one doesn't support service bus integration) and lack of important features(sessions) it's surely not a solution, but a poor workaround which works in some cases.
@alrod - I can see you are assigned to that issue. Are there any plans for solving that issue? It's almost 5 years old. If Microsoft doesn't see that as a bug it would be nice to let us - developers - know that it wouldn't be solved.
