### ISSUE TITLE
Add release notes for version 5.x.x

### ISSUE THREAD

**Issue by norvegec** [Azure/azure-functions-servicebus-extension#191]
Upgrading to a next major version should be considered carefully. Thus having release notes (which as of now outlines only ver. 4.x.x) could be very helpful.

**Comment by norvegec** [comment]
#189 could explain why it is missing in this repo

**Comment by shreyabatra4** [comment]
Please see details [here](https://github.com/Azure/azure-sdk-for-net/blob/Microsoft.Azure.WebJobs.Extensions.ServiceBus_5.3.0/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/CHANGELOG.md). Release notes for each version can be found in the release notes tab in the [package](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.ServiceBus/).
