### ISSUE TITLE
Messages in session enabled queue frequently delivered twice within same second

### ISSUE THREAD

**Issue by stewrutledge** [Azure/azure-functions-servicebus-extension#195]
Hi

We're experiencing an issue where around 1% of messages on a session queue are being delivered to an azure function twice within the same second. This doesn't seem to impact all functions/queues, rather seems isolate to one function and queue.

We are setting message_id and session_id and are using all defaults for lock time, concurrent sessions, function worker count etc..

It is a python function running in consumption consuming from a standard session enabled queue.

What is the expected behavior here and are there any settings we should be looking at?

**Comment by stewrutledge** [comment]
We’ve set scaling to a limit of 1 and it seems to have helped, but I’d like to understand why that would help.

**Comment by alrod** [comment]
@stewrutledge, what version of ServiceBus extensions are you using?
can you please share timestamp and [share your function name privately](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately)

**Comment by stewrutledge** [comment]
Hi sorry, I missed these updates. @alrod could we open this issue again?
