### ISSUE TITLE
Processing stucks after getting SessionLockLostException

### ISSUE THREAD

**Issue by alrod** [Azure/azure-functions-servicebus-extension#26]
Following code process a message only once using Microsoft.Azure.ServiceBus 3.4.0. (current package we are using in the extension) and then stcuks. The same code works fine using Microsoft.Azure.ServiceBus 4.0.0. Need to update to Microsoft.Azure.ServiceBus 4.0.0.

        static void Main(string[] args)
        {
            string cs = "";
            QueueClient client = new QueueClient(cs, "");

            SessionHandlerOptions options = new SessionHandlerOptions(ExceptionReceivedHandler)
            {
                MaxConcurrentSessions = 1,
                MaxAutoRenewDuration = TimeSpan.FromSeconds(30)
            };

            client.RegisterSessionHandler(ProcessSessionMessageAsync, options);
            Console.ReadLine();
        }

        static async Task ProcessSessionMessageAsync(IMessageSession session, Message message, CancellationToken cancellationToken)
        {
            Console.WriteLine($"Message delivary count: {message.SystemProperties.DeliveryCount}");
            await Task.Delay(50000);
        }

        static Task ExceptionReceivedHandler(ExceptionReceivedEventArgs args)
        {
            Console.WriteLine(args.Exception);
            return Task.CompletedTask;
        }

**Comment by alrod** [comment]
Blocked on Azure/azure-sdk-for-net#6410

**Comment by mpnow** [comment]
Hi @alrod, can you provide an update on what's happening with this bug? It's biting me on occasion in a production solution. Thanks!

**Comment by alrod** [comment]
@mpnow, once ServiceBus releases the fix for Azure/azure-sdk-for-net#6410 I will merge PR to update ServiceBus SDK. Probably ServiceBus will release new ServiceBus SDK next week.

**Comment by mpnow** [comment]
Hi @alrod, it looks like ServiceBus SDK 4.1.1 is out now - is that the release you were waiting for?

**Comment by mpnow** [comment]
Hi @alrod, any news on getting this fix released? It's continuing to bite me periodically in a production app. Thanks!

**Comment by mpnow** [comment]
Hi @alrod, wondering if a fix for this is out yet or, if not, when it might be?

**Comment by alrod** [comment]
the fix is out, please use:
https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.ServiceBus/4.1.0
