### ISSUE TITLE
Azure Function v2 Autocomplete Not Working

### ISSUE THREAD

**Issue by dacris** [Azure/azure-functions-servicebus-extension#34]
I have configured my host.json as follows:

```
{
   "version": "2.0",
   "extensions": {
     "serviceBus": {
       "messageHandlerOptions": {
         "autoComplete": false
       }
     }
   }
}
```

However, when I run my service bus triggered Azure function, the host log says the following:
[2019-10-11 4:48:27 PM] ServiceBusOptions
[2019-10-11 4:48:27 PM] {
[2019-10-11 4:48:27 PM]   "PrefetchCount": 0,
[2019-10-11 4:48:27 PM]   "MessageHandlerOptions": {
[2019-10-11 4:48:27 PM]     **"AutoComplete": true**,
[2019-10-11 4:48:27 PM]     "MaxAutoRenewDuration": "00:05:00",
[2019-10-11 4:48:27 PM]     "MaxConcurrentCalls": 16
[2019-10-11 4:48:27 PM]   },
[2019-10-11 4:48:27 PM]   "SessionHandlerOptions": {
[2019-10-11 4:48:27 PM]     "AutoComplete": true,
[2019-10-11 4:48:27 PM]     "MaxAutoRenewDuration": "00:05:00",
[2019-10-11 4:48:27 PM]     "MaxConcurrentSessions": 2000,
[2019-10-11 4:48:27 PM]     "MessageWaitTimeout": "00:01:00"
[2019-10-11 4:48:27 PM]   }
[2019-10-11 4:48:27 PM] }

When I do messageReceiver.DeadLetterAsync in my Azure function, there is an error message afterward saying the lock is invalid (it is trying to complete the message again).

From the log, also these are the versions I am using:
Azure Functions Core Tools (2.7.1704 Commit hash: fbab3b9c1de5ab95e3b4b6a471ead62c4f37e89c)
Function Runtime Version: 2.0.12742.0
[2019-10-11 4:48:16 PM] Building host: startup suppressed:False, configuration suppressed: False
[2019-10-11 4:48:16 PM] Loading startup extension 'Startup'
[2019-10-11 4:48:16 PM] Loaded extension 'Startup' (1.0.0.0)
[2019-10-11 4:48:16 PM] Loading startup extension 'ServiceBus'
[2019-10-11 4:48:16 PM] Loaded extension 'ServiceBus' (3.1.1.0)

I have a Startup.cs also, if it makes a difference.

**Comment by alrod** [comment]
Function runtime already provided `IConfiguration`:
https://docs.microsoft.com/bs-latn-ba/azure/azure-functions/functions-dotnet-dependency-injection#function-app-provided-services

After you added new `IConfiguration` DI starts using last added.

```
        private IServiceCollection ConfigureServices(IServiceCollection services, IConfigurationRoot root)
        {
            var existingConfigs = services.Where(svc => svc.ServiceType.Name == "IConfiguration").ToList();
            services.AddSingleton<IConfiguration>(root);

            return services;
        }
```

**Comment by dacris** [comment]
Thank you for showing me what I was doing wrong. So it turns out this line is not needed:
`services.AddSingleton<IConfiguration>(root);`

**Comment by Bubba95x** [comment]
`var tempServices = builder.Services.BuildServiceProvider();
var azureFuncConfig = tempServices.GetService<IConfiguration>();
var configBuilder = new ConfigurationBuilder()
	.AddConfiguration(azureFuncConfig)
	.SetBasePath(Environment.CurrentDirectory)
	.AddJsonFile("local.settings.json", optional: true, reloadOnChange: true)
	.AddEnvironmentVariables();`

If you want to keep your custom configuration, you can pull the IConfiguration from the DI and add it to your custom configuration.  The autocomplete will be respected and you can keep your custom providers such as key vault.

**Comment by A30006565** [comment]
Thanks @Bubba95x! Your suggestion worked like a charm. Now we have both `host.json` loading fixed and custom configs with keyVault working.

**Comment by meyunus** [comment]
@NoPanicBanick how do you add host.json configuration in this way? Is it also to be added under ConfigureAppConfiguration?

**Comment by unruledboy** [comment]
@hybridtechie where does that AddAzureAppConfiguration come from? I've added Microsoft.Extensions.Configuration 3.1.17 but I could not find it.

**Comment by unruledboy** [comment]
@NoPanicBanick same question as @meyunus

**Comment by NoPanicBanick** [comment]
Checkout this [link](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.azureappconfigurationextensions.addazureappconfiguration?view=azure-dotnet).  That extension method is for registering an Azure Configuration Service in your application.  Not to be confused with the App Settings located on your Azure Function's configuration.  App Settings should be automatically registered by the Azure Function SDK.

Similarly, the host.json registration should be handled by the Azure Function SDK.  You don't have to manually register it.  If you want to verify this; build the config in the startup, set a break point, and check the providers in the built config.  You should see a provider that contains your host.json configuration.
@unruledboy

**Comment by wilsonchenbhs** [comment]
@NoPanicBanick  I am using v3 and I finally ended up using a mixed version of your above solution, but via override of ConfigureAppConfiguration. Something like this:

```
public class Startup: FunctionStartup
{
   public override void ConfigureAppConfiguration(IFunctionsConfigurationBuilder builder)
   {
      // obtain host.json configs
      var config = builder.ConfigurationBuilder.Build();

      builder.ConfigurationBuilder
        .AddConfiguration(config) // add configs in the host.json
        .AddJson("full-path-to-your-appsettings.json")
        .AddkeyVault(......)  // you can add configs from Azure key Vault
        .AddEnvironmentVariables();
   }
}
```

And there is NO need to do sth like this `builder.Services.AddSingleton<IConfiguration>(config);`.
