### ISSUE TITLE
Sessions Enabled - host.json autoComplete `false` is ignorred

### ISSUE THREAD

**Issue by mpaul31** [Azure/azure-functions-servicebus-extension#42]
Hello,

When I have `autoComplete` set to false in my host.json and have `IsSessionsEnabled = true` on my service bus trigger the messages are being completed without me having to call `CompleteAsync` on the message session. 

This is causing lock exceptions when I try to manually complete the message.

Thanks and any update or information would be great!

**Comment by alrod** [comment]
@mpaul31, what version of `Microsoft.Azure.WebJobs.Extensions.ServiceBus` do you use? can you please try 4.1.0 and see if the latest version works for you?

**Comment by alrod** [comment]
Also you need to set in host.json:
"SessionHandlerOptions": {
      "AutoComplete": "true"
 }
https://github.com/Azure/azure-functions-servicebus-extension/blob/dev/test/Microsoft.Azure.WebJobs.Extensions.ServiceBus.Tests/ServiceBusEndToEndTests.cs#L346

Documentation here is out of date:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus#hostjson-settings
