### ISSUE TITLE
Unexpected  SessionLockLostExceptions during processing 2 different sessions

### ISSUE THREAD

**Issue by alrod** [Azure/azure-functions-servicebus-extension#43]
I'm working with a simple setup where I have AutoComplete = false and I complete the messages myself, which works as attended for the most part.
I regularly experience SessionLockLostExceptions though, even in the most basic setup where there is plenty of session-lock-time left. With a little digging I found out that my function instances quite often are injected with the wrong IMessageSession objects. I can easily tell, because the Msg.SessionId is different from the messageSession.SessionId.
It seems that the following scenario takes place:
Two messages in two different sessions are on the subscription that my function subscribes to. Then my function is triggered twice, almost simultaneously, and both sessions are correctly locked, but both function instances are injected with the same messageSession. Then when I try to complete a message with the wrong messageSession, it of course fails, but it surfaces as a SessionLockLostException, which is possibly what a lot of the others in this thread are encountering.

Copied from:
https://github.com/Azure/azure-functions-servicebus-extension/issues/16#issuecomment-559093573

**Comment by alrod** [comment]
@cgrevil, @buyckkdelaware is it reproducable in the latest package:
https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.ServiceBus/4.1.0 ?

**Comment by alrod** [comment]
Closed us duplicate #23

**Comment by buyckkdelaware** [comment]
@alrod 
It looks ok from the first tests on my side. But I did notice other cases of SessionLockLostExceptions, but they don't look related to this particular issue.
