### ISSUE TITLE
Blob binding expression to servicebus trigger property no longer works

### ISSUE THREAD

**Issue by mliesmons** [Azure/azure-functions-servicebus-extension#44]
In 4.0.0 below worked fine, in 4.1.0, I get a run-time error telling me {BlobContainerAndPath} could not be bound to (this is a public property of the ServiceBusEvent type):

            [ServiceBusTrigger("%ServiceBus:Topic%", "%ServiceBus:Subscription%", Connection = "ConnectionStrings:ServiceBus")] ServiceBusEvent serviceBusEvent,
            [Blob("{BlobContainerAndPath}", FileAccess.Read, Connection = "ConnectionStrings:Blob")] TextReader blobReader)

**Comment by solonrice** [comment]
I also just found that binding expressions fail in Singleton scopes when using a POCO object in the ServiceBusTrigger decorated parameter. Works in 3.1.1 (the version I fell back to).

**Comment by mliesmons** [comment]
> I also just found that binding expressions fail in Singleton scopes when using a POCO object in the ServiceBusTrigger decorated parameter. Works in 3.1.1 (the version I fell back to).

It is awfully quite here, I think we better repost in https://github.com/Azure/azure-webjobs-sdk/issues
