### ISSUE TITLE
 Using MessageReceiver only first time getting message from topic using Azure Function HttpTrigger

### ISSUE THREAD

**Issue by ashuthinks** [Azure/azure-functions-servicebus-extension#47]
Using MessageReceiver only first time getting messages from topic using Azure Function Httptrigger after that next time when execute Function though I have messages into service
 bus topic still getting null into variable messages.
if i stop and restart function app it work again fine for first time.

Using below code to get messages from Service Bus Topic , whats the cause?

string serviceBusConnectionString = Environment.GetEnvironmentVariable("ConnectionString");
var messageReceiver = new MessageReceiver(serviceBusConnectionString, Environment.GetEnvironmentVariable("topicName/subscriptions/subscriptionName"), ReceiveMode.PeekLock, null, 500);

var messages = await messageReceiver.ReceiveAsync(500, TimeSpan.FromSeconds(1));
i can't understand this - after every 15 minutes when LA call FA then FA should able to read new available messages but it is coming null.

[https://i.stack.imgur.com/J8Var.png](url)
Topic settings are like below - 

[https://social.msdn.microsoft.com/Forums/getfile/1526555](url)

subscription setting -
[https://social.msdn.microsoft.com/Forums/getfile/1526583](url)
why such behavior any clue?

**Comment by alrod** [comment]
@ashuthinks, do you complete the messages in the function code? `ReceiveMode.PeekLock` means that the messages will be locked for some time and you can receive null even if ServiceBusExplorer shows you there are active messages in the subscription. Can you reproduce this using simple console app instead of `HttpTrigger`?
