### ISSUE TITLE
ServiceBusTrigger is not triggered after function goes asleep

### ISSUE THREAD

**Issue by fdario-gcm** [Azure/azure-functions-servicebus-extension#5]
We have a Function App V2 that has TimeTriggers, HttpTriggers and ServiceBusTriggers, running on Consumption Plan.
Hitting the function URL or doing any HTTP request "wakes up" the function, and once the function is up and running, every message in a Service Bus queue gets picked up and processed correctly. After some idle minutes, the function, as expected, goes asleep, and it simply doesn't trigger anymore when new messages are sent to the queue.

#### Investigative information

- Timestamp: 2019-04-29T17:48:22.1330372Z
- Function App version (1.0 or 2.0): 2.0 (2.0.12427.0)
- Invocation ID: 5df55e1a-9629-4824-b9d0-b8d83fb0f6a0
- Operation ID: 131a04383fc0174da2794efe0e14ccc6
- Region: East US

#### Repro steps

1. Hit the function URL in the browser;
2. Send a message to a Service Bus queue;
3. The message gets picked up as expected;
4. Wait approximately 10 minutes for the function to go asleep;
5. Send another message to a Service Bus queue;
6. The message stays on the queue until any of the following events happen:
6.1 A Time Trigger runs;
6.2 An HttpTrigger receives a request;
6.3 The function URL is opened in a browser;
6.4. Eventually it gets picked up without any of the events above happening, but it's usually in the next day, close to 9AM. Might be related to a TimeTrigger we have running every day at 9AM, because the function should have to start moments before the TimeTrigger run time, so it would be able to pick up the remaining messages from the queue.

#### Expected behavior

Whenever a message is sent to a Service Bus Queue, the function should pick it up. If it's dormant, it should wake up and pick it up.

#### Actual behavior

As soon as a function V2 in Consumption Plan goes asleep, no more messages are picked up from a Service Bus queue or topic subscription

- At 2019-04-29 17:48:22.133Z, a message was last picked up from a Service Bus queue, because the function was awake;
- At 2019-04-29 20:32:08:226Z a message was sent to the same Service Bus queue;
- It remained in the queue until 2019-04-30T08:58:50.269Z, when it got picked up, approximately 1 minute before our daily Time Trigger runs (2019-04-30 09:00:00.006Z).

**Last time the function picked up a message before going asleep:**
**Timestamp**: 2019-04-29T17:48:22.1330372Z
**InvocationId**: 5df55e1a-9629-4824-b9d0-b8d83fb0f6a0
**Duration**: 1,664.597
**OperationId**: 131a04383fc0174da2794efe0e14ccc6

Host has shutdown at 2019-04-29T18:37:27.899Z. 
Kudu Log:
`<step title="Process Shutdown" date="2019-04-29T18:37:27.899" instance="0aa072" pid="14820,2,37" uptime="00:24:58.0367304" lastrequesttime="00:24:38.8282116" >
    <step title="Cleanup Xml Logs" date="2019-04-29T18:37:27.913" />
</step>`

**Last time the function ran and picked up a message, more than 12 hours after the last message was put in the queue, and moments before our daily TimeTrigger runs:**
**Timestamp**: 2019-04-30T08:58:50.2695977Z
**InvocationId**: 48afc4cd-824d-4bb6-97ad-293a86e6f6fd
**Duration**: 4,121.5649
**OperationId**: 73e4e02ee116ff46a2205e2e21b54f2f

#### Known workarounds

Hitting the function URL in the browser, doing any HTTP request to a HttpTrigger or having a TimeTrigger running every 5min wakes up the function and the messages are picked up as expected.

We had the function running for a couple days with a TimeTrigger running every 5 minutes and we didn't have any issues, all messages were picked up seconds after they were put in the queue.
Once we disabled that, the issue started to happen again.

#### Related information 

* Programming language used: C#
* Precompiled function

**Comment by alrod** [comment]
https://github.com/Azure/azure-functions-servicebus-extension/commit/ed08a303dba66b24d38360bb577cd2de1ced83b7
