### ISSUE TITLE
Misleading behavior/error message when using default connection for ServiceBus

### ISSUE THREAD

**Issue by lundmikkel** [Azure/azure-functions-servicebus-extension#53]
If you create a simple Azure Functions project with a ServiceBus queue trigger, you get something  like this:

```c#
[FunctionName("Function1")]
public static void Run([ServiceBusTrigger("queue", Connection = "MyConnection")] string myQueueItem, ILogger log)
{
    log.LogInformation($"C# ServiceBus queue trigger function processed message: {myQueueItem}");
}
```

Your `local.settings.json` file should then contain the connection string like this:

```js
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "MyConnection": "Endpoint=sb://...",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet"
  }
}
```
This all works fine.

If you then remove the custom connection name like this:
```c#
public static void Run([ServiceBusTrigger("queue")] string myQueueItem, ILogger log)
```
You start getting an error (as would be expected):

> Microsoft.Azure.WebJobs.ServiceBus: Microsoft Azure WebJobs SDK ServiceBus connection string 'AzureWebJobsServiceBus' is missing or empty.

So you rename the setting to `AzureWebJobsServiceBus`:
```js
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "AzureWebJobsServiceBus": "Endpoint=sb://...",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet"
  }
}
```

But that doesn't fix the problem. Instead you have to add a whole new `ConnectionStrings` section to the settings file with a completely new setting named `ServiceBus`:
```js
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet"
  },
  "ConnectionStrings": {
    "ServiceBus": "Endpoint=sb://..."
  }
}
```
This is super confusing. None of this matches the behavior for named connections or the names shown in the error message.

Is this really intended? Why not read the property the same way as for named connections? This took me way too long to figure out.

**Comment by alrod** [comment]
@lundmikkel , what version of `Microsoft.Azure.WebJobs.Extensions.ServiceBus` do you use?
I can not reproduce using 4.1.0

**Comment by lundmikkel** [comment]
I've uploaded [a small example](https://github.com/lundmikkel/azure-functions-servicebus-extension-issues-53) that doesn't seem to work. I've included the local.settings.json file with all the different ways you could try to set the connection string.

I also noticed that Azure has the following message about connection strings:

> Connection strings should only be used with a function app if you are using **entity framework**. For other scenarios use App Settings. [Learn more](https://go.microsoft.com/fwlink/?linkid=875276)

Which seems to go completely against the idea of using a connection string.

**Comment by alrod** [comment]
hmm, I just tried your project and it works for me:
```
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "AzureWebJobsServiceBus": "[my connection]",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet"
  }
}
```

**Comment by lundmikkel** [comment]
Okay, I can't really explain this, but I've just tried running the project again, and now it suddenly works :flushed:

Well, thanks for you help and time, I'll close the issue again and let you know if I should ever have problems with it again.
