### ISSUE TITLE
Uncaught MessageLockLostException when a single message is dead lettered from a message batch

### ISSUE THREAD

**Issue by elksson** [Azure/azure-functions-servicebus-extension#54]
Steps to reproduce:

`        [FunctionName("Reproduction")]
        public async Task Reproduction(
    [ServiceBusTrigger("topic", "subscription", Connection = "ServiceBusConnection")] long[] servicetypes,
    Int32[] deliveryCountArray,
    string[] lockTokenArray,
    MessageReceiver messageReceiver,
    IBinder binder,
    ILogger log)
        {
            await messageReceiver.DeadLetterAsync(lockTokenArray[0]);
        }`

**Comment by alrod** [comment]
@elksson, did you set AutoCompete to false?
https://github.com/Azure/azure-functions-servicebus-extension/blob/dev/test/Microsoft.Azure.WebJobs.Extensions.ServiceBus.Tests/ServiceBusEndToEndTests.cs#L356

This will skip completing in the code

**Comment by elksson** [comment]
@alrod I did not set autocomplete to false cause I did want the auto complete to happen if no messages needed to be dead lettered. That would be a workable solution however 99% of the time I am expecting that the function will run without any errors so I won't need to dead letter any messages and would like the trigger to handle completing them.

**Comment by elksson** [comment]
@alrod when autocomplete is enabled for single mode instead of batch does the exception get thrown if the lock is lost before autocomplete? or does the run loop swallow this exception?

**Comment by alrod** [comment]
> @alrod I did not set autocomplete to false cause I did want the auto complete to happen if no messages needed to be dead lettered. That would be a workable solution however 99% of the time I am expecting that the function will run without any errors so I won't need to dead letter any messages and would like the trigger to handle completing them.

If you want to use `DeadLetterAsync` in your code you need to set AutoComplete="false".

**Comment by alrod** [comment]
> @alrod when autocomplete is enabled for single mode instead of batch does the exception get thrown if the lock is lost before autocomplete? or does the run loop swallow this exception?

@elksson for single mode the exception also get thrown if the lock is lost before autocomplete.

**Comment by elksson** [comment]
@alrod I guess that makes sense maybe would could change this to a feature request instead of a bug fix and see how the community feels? 

I would propose that we make a 3rd mode for autocomplete, true, false, and hybrid

When the binding is in "hybrid" mode then the binding would track any calls to release, defer, complete the locks and then skip them when the autocomplete was performed.

**Comment by alrod** [comment]
@elksson, we are using ServiceBus SDK and there are no such thing as "hybrid" mode unfortunately

**Comment by elksson** [comment]
@alrod is it not possible to build such a "hybrid" mode into the trigger binding itself and essentially the binding could proxy all the requests to the receiver and track the ones that are already completed or released, or deadlettered?
