### ISSUE TITLE
host.json options not documented

### ISSUE THREAD

**Issue by elksson** [Azure/azure-functions-servicebus-extension#58]
The Host.json options need updated to document the options added for issue #15 

https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus?tabs=csharp#hostjson-settings

**Comment by elksson** [comment]
Also the JSON Schema for the host file needs updated so that visual studio can provide intellisense for these options. 
http://json.schemastore.org/host

**Comment by alrod** [comment]
`host.json` options are updated for all runtime versions:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus?tabs=in-process%2Cextensionv5%2Cextensionv3&pivots=programming-language-javascript#hostjson-settings
