### ISSUE TITLE
4.1.0 Unable to resolve binding parameter error.

### ISSUE THREAD

**Issue by natelaff** [Azure/azure-functions-servicebus-extension#60]
After updating to 4.1.0, triggers are failing to index due to binding paramters.

For example, create a new SendGrid trigger and the function will error with the {CustomerEmail} binding for the To property.

Unable to resolve binding parameter CustomerEmail. Binding expressions must map to either a value provided by the trigger or a property of the value the trigger is bound to, or must be a system binding expression (e.g. sys.randguid, sys.utcnow, etc.).

Maybe related to #48 ?

**Comment by alrod** [comment]
Closing as duplicate (#44). Should be closed in current sprint.
@natelaff, thanks for reporting.
