### ISSUE TITLE
Could not load assembly

### ISSUE THREAD

**Issue by sherif-botros** [Azure/azure-functions-servicebus-extension#63]
Can I get to get some guidance on debugging a Queue locally?

1. I am using DependencyInjection via a Startup class that is a FunctionsStartup
2. I am using a ServiceBusTrigger attribute
3. I have the extensionBundle in host.json as 
`{
  "version": "2.0",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[1.*, 2.0.0)"
  }
}`
4. and the library Reference in the csproj file as `
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="4.1.0" />`

but am getting
`
[4/02/2020 4:05:24 AM] A host error has occurred during startup operation 'd751453d-5c4d-4e9f-a564-ebb4024e538f'.
[4/02/2020 4:05:24 AM] System.Private.CoreLib: Could not load file or assembly 'Microsoft.Azure.WebJobs.ServiceBus, Version=4.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621). System.Private.CoreLib: Could not load file or assembly 'Microsoft.Azure.WebJobs.ServiceBus, Version=4.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.`

If I remove the extensionBundle I get an error
` The 'xxxxxFunction' function is in error: The binding type(s) 'serviceBusTrigger' are not registered. Please ensure the type is correct and the binding extension is installed.`

**Comment by alrod** [comment]
@sherif-botros, can you please provide a simple project with repo?

**Comment by sherif-botros** [comment]
Hey mate, thanks for you prompt reply.  
I just got over that issue by making use of the latest version of [Azure Functions Core Tools](https://github.com/Azure/azure-functions-core-tools#readme) and in particular removing [extensionBundle](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=windows#extension-bundles) from host.json and running the `[func extensions install](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=windows#register-individual-extensions)`

however, I am now facing an issue where Dependency Injection is unable to resolve my service and type 

`[5/02/2020 1:46:31 AM] Message processing error (Action=UserCallback, ClientId=QueueClient1statements, EntityPath=statements, Endpoint=hvos-sb-hiip-int.servicebus.windows.net)
[5/02/2020 1:46:31 AM] Microsoft.Extensions.DependencyInjection.Abstractions: Unable to resolve service for type 'xyz.IACommands' while attempting to activate 'xyz.AbcFunction'.`

csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <AzureFunctionsVersion>v2</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.0.0" />
    <PackageReference Include="Microsoft.Azure.ServiceBus" Version="4.1.1" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="4.1.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="3.0.10" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator" Version="1.0.2" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="3.1.1" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Domain\src\xyz.csproj" />
    <ProjectReference Include="..\..\Services\xyz.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

local.settings.json
```json
{
    "IsEncrypted": false,
    "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet",
    "Statements": "Endpoint=sb://xyz.windows.net/;SharedAccessKeyName=manager;SharedAccessKey=lRxxx2D0="
  }
}
```

host.json
```
{
  "version": "2.0",
  "logging": {
    "ApplicationInsights": {
      "LogLevel": {
        "Default": "Information",
        "Microsoft": "Error",
        "System": "Warning"
      }
    },
    "logLevel": {
      "System": "Warning",
      "Microsoft": "Warning",
      "default": "Information"
    }
  }
}
```

Startup.cs
```c#
using other.projects
using Microsoft.Azure.Functions.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection;

[assembly: FunctionsStartup(typeof(Startup))]
namespace Some.Function{
    public class Startup : FunctionsStartup {
        public override void Configure(IFunctionsHostBuilder builder) {
            builder.Services.AddLogging();
            builder.Services.AddScoped<IRepository, xRepositoryImpl>();
            builder.Services.AddScoped<IACommands, xCommandsImpl>();
        }
    }
}
```

Function.cs
```c#
using System;
using System.Threading.Tasks;
using other.proj;
using Microsoft.Azure.WebJobs;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;

namespace xFunction{
    public class xyFunction {
        private readonly IACommands _aCommands;
        private readonly IRepository _xRepository; 
        public RequestStatementFunction(IACommands commands, IRepository repository, ILogger log){
            _aCommands = commands;
            _xRepository = Repository;
            _logger = log;
        }

        [FunctionName("RequestStatementFunction")]
        public async Task Run([ServiceBusTrigger("queuename", Connection = "conn", IsSessionsEnabled = true)]string queueItem) {
            try {
                _logger.LogInformation($"Queue trigger function found a message: {queueItem}");
                _aCommands.Execute(queueItem);
            }
            catch (Exception e) {
                Console.WriteLine(e);
                _logger.LogError(e, "");
                throw;
            }
        }
    }
}
```
My main aim is to debug locally obviously.
Can you point to anything I am missing?

**Comment by sherif-botros** [comment]
.net core 3.0 🗡

**Comment by grahambunce** [comment]
@sherif-botros I know this is your issue, but I've got a similar problem where my 2.1 function is trying to load 3.2 - logs state "Loaded extension 'ServiceBus' (3.2.0.0)" but my Functions project references Microsoft.Azure.WebJobs.ServiceBus, Version=4.0.0.0.

I get this error:

```
[16/02/2020 17:44:16] A host error has occurred during startup operation '9c264b67-b73c-4964-9c08-e7ff77e68a3c'.
[16/02/2020 17:44:16] System.Private.CoreLib: Could not load file or assembly 'Microsoft.Azure.WebJobs.ServiceBus, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621). System.Private.CoreLib: Could not load file or assembly 'Microsoft.Azure.WebJobs.ServiceBus, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
[16/02/2020 17:44:16] Stopping JobHost
[16/02/2020 17:44:18] Building host: startup suppressed: 'False', configuration suppressed: 'False', startup operation id: '65abc3c0-ba11-468d-8598-998588c6daab'
[16/02/2020 17:44:18] Reading host configuration file 'C:\dev\Consumer.Function\bin\Debug\netcoreapp2.1\host.json'
[16/02/2020 17:44:18] Host configuration file read:
[16/02/2020 17:44:18] {
[16/02/2020 17:44:18]   "version": "2.0",
[16/02/2020 17:44:18]   "extensionBundle": {
[16/02/2020 17:44:18]     "id": "Microsoft.Azure.Functions.ExtensionBundle",
[16/02/2020 17:44:18]     "version": "[1.*, 2.0.0)"
[16/02/2020 17:44:18]   }
[16/02/2020 17:44:18] }
```

Your comment to close ".net core 3.0" doesn't really make any sense. Can you explain further?

**Comment by thomaslevesque** [comment]
I have the same issue. I'm targeting .NET Core 3.1

Please reopen!

**Comment by srini247** [comment]
i'm having the same issue targeting .NET Core 3.1. please advice

**Comment by srini247** [comment]
My issue got resolved after downgrading Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator to 1.1.3 from 1.1.8.
