### ISSUE TITLE
Logging shows invalid session id

### ISSUE THREAD

**Issue by Zenuka** [Azure/azure-functions-servicebus-extension#64]
In application insights I'm getting strange session ids with some of my trace telemetry. I think it's because of this line: https://github.com/Azure/azure-functions-servicebus-extension/blob/4c4ef3252112bc822a5c80a26824b12146330650/src/Microsoft.Azure.WebJobs.Extensions.ServiceBus/Triggers/ServiceBusTriggerInput.cs#L88

An example session id is:

prop__SessionId | 12/31/9999 11:59:59 PM
-- | --

**Comment by alrod** [comment]
closed
