### ISSUE TITLE
Allow cardinality so can do batch in non-.NET

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-servicebus-extension#65]
We now support batch https://github.com/Azure/azure-functions-servicebus-extension/issues/15 but I dont see a way to describe batch messages for non-.NET.  In Event Hubs we have a property `cardinality` that can be set to `one` or `many` in function.json to describe if should be batched for non-.NET.  If not this, at least want to understand how could take advantage of batch trigger outside of C#

**Comment by alrod** [comment]
@jeffhollan, I tested `cardinality many` in `function.json` before the batch release. This should work.
