### ISSUE TITLE
Release Cadence? 

### ISSUE THREAD

**Issue by bmwaechter** [Azure/azure-functions-servicebus-extension#66]
Was wondering what the release cadance is or if there is a place I can check the status of the next release to nuget (CICD pipeline for releases?).  PR completed a bit ago (#62 ) has changes I want to incorporate into my app.  
Thanks!

**Comment by alrod** [comment]
PR #62 is released in https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.ServiceBus/4.1.1
