### ISSUE TITLE
ServiceBusTrigger on Consumption plan does not keep w3wp process alive to receive messages

### ISSUE THREAD

**Issue by swettstein** [Azure/azure-functions-servicebus-extension#67]
**Problem:**
When using a simple .NET Azure Function with one ServiceBusTrigger, the w3wp process disappears and will not receive messages until navigating to the function definition on Azure portal. There's probably something happening that is unexpectedly killing the process but I cannot find what it is in Application Insights or Kudu.

**Sample Code:**
```
public class ServiceBus
{
    private readonly IServiceBusMessageConsumer _serviceBusMessageConsumer;

    public ServiceBus(IServiceBusMessageConsumer serviceBusMessageConsumer)
    {
        _serviceBusMessageConsumer = serviceBusMessageConsumer;
    }

    [FunctionName("QueueConsumer")]
    public async Task QueueConsumer([ServiceBusTrigger("%QueueName%")] Message message)
    {
        await _serviceBusMessageConsumer.ConsumeAsync(message);
    }
}
```

**Additional Details:**
Using packages:
- Microsoft.NET.Sdk.Functions 1.0.31
- Microsoft.Azure.WebJobs 3.0.14
- Microsoft.Azure.WebJobs.Extensions.ServiceBus 4.1.0

**Workaround:**
Add a timer trigger that fires every ten minutes:
```
[FunctionName("KeepAlive")]
public void KeepAlive([TimerTrigger("0 */10 * * * *")]TimerInfo timerInfo) { }
```

**Comment by alrod** [comment]
A consumption plan function app will be stopped if there are no new messages in ServiceBus. When scale controller detects new messages the function app will be started automatically once again.
Can you please:
1. Disable KeepAlive timer.
2. Share you function app privately: https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately
3. Provide a timestamp in UTC when you expect your service bus should be triggered.

**Comment by swettstein** [comment]
Here is the timestamp and execution id: 2020-03-11T20:09:21.593 [Information] Executing 'Function' (Reason='', Id=c08eee67-6f7d-4e55-a0ff-72dc234d3232)
Region is East US
Message Enqueue Time: 
![image](https://user-images.githubusercontent.com/16578892/76461859-ae6c1680-63ae-11ea-896f-316d44961afc.png)

**Comment by alrod** [comment]
I do not see function executions for 'I..r' function around 3/11/2020 20:38 UTC.
Can you please check if you have another function app/slot/local app pointed to the same service bus entity?

Also I noticed you removed "KeepAlive" function. Did you fix the issue?

**Comment by swettstein** [comment]
that's precisely the problem. the message was enqueued at 20:38 but the function did not process it. the job host had shut down the worker process.

i removed the KeepAlive on purpose to recreate the problem.

**Comment by alrod** [comment]
How did you set queue name and SB connection string? Are they regular app settings?

**Comment by swettstein** [comment]
the connection string is a regular app setting but endpoint (queue) is not. this code is definitely the problem where i set the endpoint name app setting and force EnvironmentVariablesConfigurationProvider to reload. what i don't know is why this breaks the Service Bus Scale Monitor. do you know why?

```
public class EndpointSetter : IEndpointSetter
{
    private readonly EndpointInfo _endpointInfo;
    private readonly IConfiguration _configuration;

    public EndpointSetter(EndpointInfo endpointInfo, IConfiguration configuration)
    {
        _endpointInfo = endpointInfo;
        _configuration = configuration;
    }

    public void SetEndpoint()
    {
        Environment.SetEnvironmentVariable("Endpoint", _endpointInfo.EndpointName, EnvironmentVariableTarget.Process);
        var root = _configuration as ConfigurationRoot;
        root?.Providers.OfType<EnvironmentVariablesConfigurationProvider>().SingleOrDefault()?.Load();
    }
}
```

**Comment by swettstein** [comment]
Sorry, I should have been more clear. The code I posted previously was in a startup code block. When I take out that code, everything works as expected and the scale monitor is able to scale up and down correctly. But with that code, it does not scale up. What is it about that code that breaks the service bus scale monitor?

**Comment by AvigdorLevy** [comment]
Hi,
I have the same issue( V3 function,Consumption Plan,ServiceBusTrigger Topic/Subscription) but the connection string is stored in AppConfiguration azure resource(which references keyValut for the actual service bus connection string)
Could it be that the scale controller cant find the actual connection string when it stored in the App Configuration resource and thus cant scale and start an instance once a message arrives to the topic and the function is idle(again when "refreshing" using the portal all works...)?

**Comment by drdamour** [comment]
@swettstein that's exactly what @alrod was saying...since the scale controller can't detect your configuration (cause it looks at app setting directly based on attributes/manifest files and doesn't know about/can't detect your reconfiguration code) the scale controller doesn't know what to monitor and thus never knows to start your function up

**Comment by swettstein** [comment]
@drdamour yep. we removed the offending code and set the queue name on deployment rather than startup.

this can be closed.

**Comment by alrod** [comment]
this can be closed.
