### ISSUE TITLE
ServiceBusTrigger does not trigger on consumption plan with Managed Identity

### ISSUE THREAD

**Issue by KristofC4T** [Azure/azure-functions-servicebus-extension#68]
# Description
I'm having a problem in the following combination:
- function app on a consumption plan
- function with ServiceBusTrigger
- connection string to the service bus in app settings, looks like "Endpoint=sb://xxxxx.servicebus.windows.net;Authentication=Managed Identity;"
- on the SB, the function app has 'Azure Service Bus Data Receiver' and 'Azure Service Bus Data Sender' rights
- message is waiting on service bus topic
- function app is deployed using Azure App Service deploy task on Azure DevOps

## Actual Behavior
message is not picked up by function app and remains on topic

## Expected Behavior
message is picked up and processed

## Additional info
Only when the function app is accessed in the azure portal will it become active and pick up the message. Another message placed on the queue right after is also processed. After letting it idle for an hour and placing another message on the queue, it is not picked up until someone accessed the app through the portal.

Granting Owner rights on the SB for the function app did not resolve, choosing different deployment methods in the Azure App Service deploy task did not resolve, removing the semicolon at the end of the connection string (as was suggested here: https://github.com/Azure/azure-functions-host/issues/3966#issuecomment-464242142) did not resolve the issue.

Only when the connectionstring was altered to use a SAS token, did it work as expected that messages got picked up right after deploy and after idle time.

Microsoft.Azure.WebJobs.Extensions.ServiceBus Version="4.1.0"
Microsoft.NET.Sdk.Functions Version="3.0.3"

**Comment by alrod** [comment]
The behavior is expected as a consumption plan function app uses internal scale controller to wake up the function app when new service bus messages are detected:
1. A consumption function app becomes active when it is opened in the portal. ServiceBus trigger works fine as the function app has rights on SB side.
2. When there are no new messages in SB the function app becomes non-active.
3. Scale controller tries to detect new messages in SB and wake up the function app if so. But this can't be done us Scale Controller does not have rights on SB side => ServiceBustrigger does not trigger.

As workaround is using AppService plan or a connection string without "Managed Identity".

**Comment by b10-dslappendel** [comment]
@alrod It's been a year; are there any plans to support triggers on consumption plan in combination with managed identity? It would be great if I don't have to shuffle around with keys on consumption plan.

**Comment by willyt150** [comment]
@b10-dslappendel and @KristofC4T

We've got a .net 6 Isolated functionusing the Microsoft.Azure.Functions.Worker.Extensions.ServiceBus v5.0.0-beta.6 nuget package and following their documentation for auth via Managed Identity, I was able to get our consumption function to trigger properly (w/o navigating to it in the Azure Portal). We're hoping the nuget package gets a GA release soon, but no clue on that. @alrod do you have any news on when this will GA?

I waited 30 minutes after processing first and it triggered, and then just to be extra sure, I waited another 60 minutes w/ 0 service bus messages sent in, to ensure the function truly shut down. Then sending in message, the function triggered.

Here are the docs I followed to get me there.
https://docs.microsoft.com/en-us/azure/azure-functions/functions-identity-based-connections-tutorial-2#add-a-service-bus-triggered-function
https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference?tabs=blob#common-properties-for-identity-based-connections

**Comment by andrewkittredge** [comment]
I ham still having this problem.  I am on Microsoft.Azure.WebJobs.Extensions.ServiceBus version 5.5.1.
