### ISSUE TITLE
InvalidOperationException: Microsoft Azure WebJobs SDK ServiceBus connection string 'AzureWebJobsServiceBus' is missing or empty.

### ISSUE THREAD

**Issue by Andreas-Lehmann** [Azure/azure-functions-servicebus-extension#7]
When using the ServiceBus extension in .Net core the default configuration behaviour is not equal to the base WebJob SDK.

We use a simple `appsettings.json` file for configuration. There we have a section like:
```json
{
  "MySection": {
    ...
  },
  "ConnectionStrings": {
    "AzureWebJobsDashboard": "DefaultEndpointsProtocol=https;AccountName=xyz;AccountKey=***==;EndpointSuffix=core.windows.net",
    "AzureWebJobsStorage": "DefaultEndpointsProtocol=https;AccountName=xyz;AccountKey=***==;EndpointSuffix=core.windows.net",
    "AzureWebJobsServiceBus": "Endpoint=sb://xyz.servicebus.windows.net/;SharedAccessKeyName=SendListenCredentials;SharedAccessKey=***"
  }
}
```
The `AzureWebJobsDashboard` and `AzureWebJobsStorage` settings are read by the WebJob SDK as expected without any additional configuration.
When we use the `Microsoft.Azure.WebJobs.ServiceBus` extension without any custom configuration, an `InvalidOperationException` exception is thrown:

`InvalidOperationException: Microsoft Azure WebJobs SDK ServiceBus connection string 'AzureWebJobsServiceBus' is missing or empty.`

We use this c# code for initialization:

```csharp
IHost host = new HostBuilder()
    .UseEnvironment(environment)
    .ConfigureWebJobs(b =>
    {
        b.AddAzureStorageCoreServices()
        .AddTimers()
        .AddServiceBus()
        .AddAzureStorage();
    })
    .Build();
```
The storage connection strings are used as expected from the `ConnectionStrings` section of our configuration file.

Currently we work around that issue giving the connection string to the `.AddServiceBus()` operation.
```csharp
.AddServiceBus(c => c.ConnectionString = myConnectionString)
```
Actually our implementation reads the value from the configuration section above, but we would expect this to be the default/fall back behaviour of the ServiceBus extension and it would align its configuration well with the basic WebJob SDK implementation.

**Comment by brettsam** [comment]
If you use "ServiceBus" as your connection string name in appsettings.json, it should work. But this is an inconsistency that we should fix.

Looks like we need to change this line:
https://github.com/Azure/azure-functions-servicebus-extension/blob/master/src/Microsoft.Azure.WebJobs.Extensions.ServiceBus/Config/ServiceBusWebJobsBuilderExtensions.cs#L43

... to instead call GetWebJobsConnectionString, which will perform the lookups as expected.
https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/Extensions/IConfigurationExtensions.cs#L14

**Comment by alrod** [comment]
https://github.com/Azure/azure-functions-servicebus-extension/commit/ed08a303dba66b24d38360bb577cd2de1ced83b7

**Comment by damianfijorek** [comment]
It seems that bug was reintroduced in v4.x dotnet-isolated. The only way to make it work is to add connection string to Configuration in Azure Portal. It seems that there is no equivalent workaround for isolated functions.

**Comment by codebeaulieu** [comment]
Just ran into this in a fresh project. Setting the connection string key to "ServiceBus" fixed the issue.
