### ISSUE TITLE
Linux consumption based function with service bus trigger stops processing after 10 minutes

### ISSUE THREAD

**Issue by tomgallard** [Azure/azure-functions-servicebus-extension#71]
#### Check for a solution in the Azure portal

My dotnetcore3.1 linux function app seems to stop processing messages after 10 minutes (which is also the timeout setting I have in host.json. I am using a zip based deployment to Azure storage referenced using the WEBSITE_RUN_FROM_PACKAGE application setting.

I am using a service bus trigger, with autocomplete set to false. I am completing/failing the messages in code, and am confident there are no code paths where messages are not being completed or failed.

After the function stops processing messages if I go back into the function on azure portal, it will restart processing messages.

![image](https://user-images.githubusercontent.com/637795/75022203-8f542600-548d-11ea-8484-dec817c9d8f0.png)

I also never see the function scaling beyond 1 instance.

#### Investigative information

Please provide the following:

- Timestamp: 2020/02/21 08:57:00
- Function App version (1.0 or 2.0): 3
- Function App name: v4api-pwt-multi-image-support-jobconsumer
- Function name(s) (as appropriate): ReceiveScheduledTask
- Invocation ID:
- Region: North Europe

#### Repro steps

Provide the steps required to reproduce the problem:

1. Click function name in azure portal, observe in app insights live metrics that messages are being processed. Only 1 instance appears processing messages regardless of queue length
2. Wait 10 minutes
3. Observe messages are no longer being processed. 
4. Click function name in azure portal. Observe messages start being processed again

#### Expected behavior

Provide a description of the expected behavior.

Function should continue processing messages for longer than 10 minutes.

#### Actual behavior

Messages stop being processed after 10 minutes

#### Related information 

Provide any related information 

Dotnetcore 3.1
Service bus binding- 
* Bindings used

**Comment by tomgallard** [comment]
Thanks- I have worked around by not using a custom INameResolver. It is very concerning that this is not mentioned in the docs anywhere, nor are any compile time errors/warnings, or run time errors/warnings evident - it just fails silently!

**Comment by alrod** [comment]
+ @jeffhollan for updaiing docs
