### ISSUE TITLE
service bus trigger connection usage

### ISSUE THREAD

**Issue by JonasSamuelsson** [Azure/azure-functions-servicebus-extension#74]
We have a system that uses service bus queues & topics/subscriptions for service to service communication. Web api:s and webjobs with service bus triggers, everything is hosted in azure app services.

We've had issues with SNAT ports exhaustion. During our investigations in trying to figure out the root cause to our problems we can see that the webjobs process has established a lot of connections, seems to be service bus connections from the port number (5671), haven't counted them but it looks like one per trigger.

![image](https://user-images.githubusercontent.com/2103937/78041123-a598b000-7370-11ea-92e4-6e2e1a97dcfb.png)

Is this expected?

According to https://4lowtherabbit.github.io/blogs/2019/10/SNAT/ we are limited to 128 outgoing ports. We are following recommended best practices to reuse http clients, enable database connection pooling, etc but if the service bus connections aren't reused we suspect that might be a reason for why we are having issues.

Any feedback or suggestions would be greatly appreciated.

**Comment by alrod** [comment]
>haven't counted them but it looks like one per trigger.Is this expected?

Yes, we have an active connection per service bus trigger to monitor changes in ServiceBus entity.
How many SB triggers do you have in your function app?

As workaround you can try:
- split the function app to multiple function apps
- try to scale up/scale out for App Service plan (https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox#cross-vm-numerical-limits)

**Comment by JonasSamuelsson** [comment]
The biggest one currently has 64 triggers but we expect that number to increase.

Is it possible to reuse connections between MessageReceivers if they target the same namespace but different entity paths?

We have talked about moving away from webjobs to functions on a consumption plan so that the api & webjobs/functions gets their own set of SNAT ports.

**Comment by alrod** [comment]
>Is it possible to reuse connections between MessageReceivers if they target the same namespace but different entity paths?

No, it's not possible. Each MessageReceiver must have an active connection to SB namespace/SB entity to listen for new messages. The best practice is to stay below 100 parallel connections to the same service bus namespace.

In case of consumption plan:
1 worker allocated = 64 outgoing ports (sb triggers). Good.
2 worker allocated = 128 outgoing ports (sd triggers). Most likely you will start to see SNAT port issues.

**Comment by JonasSamuelsson** [comment]
When you say that it's a best practice to stay below 100 connections do you mean that from a service bus perspective or webjobs/functions perspective?

What is a worker? I've never heard about it with functions before and can't find any information about it, do you have a link?

**Comment by alrod** [comment]
>When you say that it's a best practice to stay below 100 connections do you mean that from a service bus perspective or webjobs/functions perspective?

From "webjobs/functions perspective". I mean to have <100 SNAT ports allocated to the same external endpoint.

>What is a worker? I've never heard about it with functions before and can't find any information about it, do you have a link?

worker = instance
https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale#consumption-plan

**Comment by JonasSamuelsson** [comment]
> > Is it possible to reuse connections between MessageReceivers if they target the same namespace but different entity paths?
> 
> No, it's not possible. Each MessageReceiver must have an active connection to SB namespace/SB entity to listen for new messages.

You are probably correct on this but `MessageRecevier` have a constructor taking both a connection & entityPath (https://github.com/Azure/azure-service-bus-dotnet/blob/dev/src/Microsoft.Azure.ServiceBus/Core/MessageReceiver.cs#L139) which to me indicates that the connection can be reused between receivers (like http message handlers can be reused by multiple http clients) but maybe that is not the case.

**Comment by alrod** [comment]
@JonasSamuelsson , it turned out you are right, we are going to add reusing of the connection:
Closing as duplicate:
https://github.com/Azure/azure-functions-servicebus-extension/issues/123
