### ISSUE TITLE
Function throws "Message processing error" after calling CompleteAsync/AbandonAsync on a session enabled topic

### ISSUE THREAD

**Issue by sabrite** [Azure/azure-functions-servicebus-extension#77]
Hi guys, I have a session enabled topic in Service Bus. My azure function tries to complete or abandon the message inside catch statements (depending on when I dont want to reprocess it). The code works fine but there is always an exception logged by runtime saying:

Microsoft.Azure.ServiceBus: Operation is not valid due to the current state of the object.

Here is basic version of my func
![image](https://user-images.githubusercontent.com/5325072/78472732-8342d000-777e-11ea-8a39-0a32b49b23a9.png)

The host.json has autoComplete set to false. If I call CompleteAsync, the message is removed from the topic as expected and retried if AbandonAsync is called. The only thing I want to understand is why the function runtime throws the error:

Message processing error (Action=Complete, ClientId=SubscriptionClient1BenefitTransfer/BenefitTransferSubscriber, EntityPath=BenefitTransfer/Subscriptions/BenefitTransferSubscriber, Endpoint=dev-abc-consumer.servicebus.windows.net)
Microsoft.Azure.ServiceBus: Operation is not valid due to the current state of the object.

Any thoughts? Thanks,

**Comment by AndyWorral** [comment]
I'm getting having similiar issue except I am using autocomplete for the message.  The process succeeds and then fails in marking complete.  (blured a bunch of things in case they were private, probably did more then needed)

![image](https://user-images.githubusercontent.com/624040/83819097-01482800-a697-11ea-837b-02d34ed3b812.png)

**Comment by AndyWorral** [comment]
I think in my case I needed to adjust the maxAutoRenewDuration for servicebus settings in host.json.  I am surprised that this value doesn't default to the functionTimeOut as I would assume in most cases you would want them to love for the same amount of time.
```
{
  "version": "2.0",
  "functionTimeout": "12:00:00",
  "extensions": {
    "serviceBus": {
      "sessionHandlerOptions": {
        "messageWaitTimeout": "00:00:30",
        "maxAutoRenewDuration": "12:00:00",
        "maxConcurrentSessions": 16
      }
    }
  }
}
```

**Comment by alrod** [comment]
@sabrite, is adjusting maxAutoRenewDuration helped?

**Comment by sabrite** [comment]
Thanks Alrod - I will test it out and get back.

**Comment by sabrite** [comment]
@alrod  nope - still the same.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/5325072/163768739-5f91467b-05b0-4eee-b273-fc40702cdc2a.png)

**Comment by sivaraman27** [comment]
@sabrite Did you got any solution for the above issue? I'm facing the same issue.
