### ISSUE TITLE
Complete action fails on service bus messages because of expired lock

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-functions-servicebus-extension#82]
Repro steps
1. Create a function app with a function using service bus topic trigger on core tools
2. Add the following line of code in the function to cause it run longer than the default lock duration
`Thread.Sleep(45 * 1000);`
3. Build the function app and make a copy of the function app
4. Start both function apps by passing in different ports to core tools
   Function app1:`func host start --port 7072`
   Function app 2: `func host start --port 7071`
5. Add 200 messages to the service bus topic

Here is the function app i used for repro: [project zip](https://github.com/Azure/azure-functions-servicebus-extension/files/4560828/FunctionApp48.zip)

Expected results:
1. No conflict or lock renewal failures

Actual results
1. Both function apps cannot perform complete action and start throwing lock lost exception
`Microsoft.Azure.ServiceBus: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue`

**Comment by alrod** [comment]
`Thread.Sleep` affects receiving. The is issue not reproducible with await `Task.Dealy(45000)`
