### ISSUE TITLE
IMessageSession parameter not recognized in Azure Function with Service Bus trigger

### ISSUE THREAD

**Issue by mronnlun** [Azure/azure-functions-servicebus-extension#83]
I have this function

`[FunctionName("MyFunction")]
        public static async Task Run([ServiceBusTrigger("myqueue", Connection = "MyBusConnString", IsSessionsEnabled = true)]Message message, IMessageSession session, ILogger log)
`

When executing I get this error:

> The 'MyFunction' function is in error: Microsoft.Azure.WebJobs.Host: Error indexing method 'MyFunction'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'session' to type IMessageSession. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).

I am referencing the following nuget packages:
Microsoft.Azure.WebJobs.Extensions.ServiceBus version 4.1.1
Microsoft.NET.Sdk.Functions version 3.0.7

How can I access the session from the function?

**Comment by peterson1** [comment]
I'm stuck here as well.
Anyone knows how to get IMessageSession from a FunctionApp service bus trigger?

**Comment by alrod** [comment]
You need to bind to `IMessageSession messageSession`.

**Comment by peterson1** [comment]
I did the same thing as @mronnlun .
I thought this was the way to do it, but I got the same error as him.
What's the correct way to bind to `IMessageSession`?

**Comment by alrod** [comment]
The function parameter name must be `messageSession`
