### ISSUE TITLE
Is it Possible to Trigger/Bind Function to SB Queue Using MSI Instead of ConnectionString that Contains a Key?

### ISSUE THREAD

**Issue by countchivas** [Azure/azure-functions-servicebus-extension#9]
Wondering if this is possible.

Thank you!

**Comment by alex-zyl** [comment]
@countchivas 
It's not supported out-of-the-box yet. 
There's a PR for adding MSI support, but it seems to be stale:
https://github.com/Azure/azure-webjobs-sdk/pull/2041

**Comment by alrod** [comment]
it's not supported

**Comment by a116957** [comment]
@alrod Is there any possible date from MS to release the feature?

**Comment by charlesw23** [comment]
Will it ever be supported?

**Comment by kannannet** [comment]
@charlesw23  @alrod I think this is supported now [ https://blog.darkloop.com/post/using-service-app-managed-identity-with-azure-functions-service-bus-bindings](url)

**Comment by countchivas** [comment]
Only for system managed identities, I believe

**Comment by kannannet** [comment]
@charlesw23 @alrod  I think this is supported now

 [ https://blog.darkloop.com/post/using-service-app-managed-identity-with-azure-functions-service-bus-bindings](url)

@countchivas  yeah this works on system managed identities, even this was commented as unintentional behavior by Microsoft team in the feedback forum and said that it will be removed in the future releases, but I can see that this still works with the latest packages too

@alrod  will it be ideal to use this feature considering that the support is still working with the latest package??
