### ISSUE TITLE
CancellationToken for [ServiceBusTrigger] is never cancelled during graceful shutdown

### ISSUE THREAD

**Issue by mattbrooks2010** [Azure/azure-functions-servicebus-extension#93]
#### Repro steps

1. Create a new .NET Core console app targeting `netcoreapp2.1`. 

1. Configure a `HostBuilder`.

1. Call `ConfigureWebJobs` on the `HostBuilder` and call `AddServiceBus`. Provide a Service Bus Namespace connection string.

1. Add a WebJob function using `[ServiceBusTrigger]`. Add a `CancellationToken` parameter. Add an `ILogger` to log the value of the `CancellationToken.IsCancellationRequested` property.

1. Deploy to an Azure App Service as a continuous WebJob.

1. Queue some messages on the queue identified by the `[ServiceBusTrigger]`.

1. Stop the WebJob via the App Service resource in the Azure Portal.

#### Expected behavior

1. The `CancellationToken` should get cancelled for functions already being executed.

1. No further messages on the queue should get processed, i.e. no further functions invocations should run.

#### Actual behavior

1. The `CancellationToken` never gets cancelled. The `CancellationToken.IsCancellationRequested` property is always `false`. 

1. Messages on the queue continue to be processed until the Azure host terminates the process.

1. A `CancellationToken` passed to a second function using `[TimerTrigger]` appear to work as expected.

#### Related information 

* Using [Microsoft.Azure.WebJobs](https://www.nuget.org/packages/Microsoft.Azure.WebJobs/3.0.3) v3.0.3
* Using [Microsoft.Azure.WebJobs.Extensions](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions/3.0.1) v3.0.1
* Using [Microsoft.Azure.WebJobs.Extensions.ServiceBus](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.ServiceBus/3.0.2) v3.0.2

**Comment by fabiocav** [comment]
Moving this to sprint 81 as @soninaren proceeds with his investigation here.

**Comment by soninaren** [comment]
@mattbrooks2010, I went through the code you posted on the issue. My findings on the topic are below.

-  In your code you are checking for `cancellationToken.IsCancellationRequested` everyone second in a loop 30 times. Which may or may not be effective. To give your code best chance to react once cancellation toke is set is by registering a callback on the token. Below is the sample function code.

    ```C#
    [FunctionName("ServiceBusFuncion")]
            public static void Run([ServiceBusTrigger("myqueue", Connection = "sbconnection")]string myQueueItem, ILogger log, CancellationToken token)
            {
                token.Register(() =>
                {
                    log.LogInformation("cancel");
                });
           }
    ```
-  In my tests i did see cancellation token being set and i was able to capture the cancelled state in my application insights logs. That being said we can certainly make this more graceful and give the function code more time to react and perform graceful shutdown.
- We have a work item to implement drain mode API, The API will essentially signal the worker instance, before it is shut down / taken away for maintenance or for some other purpose. Once the API is called: 
    1. All the listeners for extensions would stop fetching more data for execution.
   2. Cancel would be called on the cancellation token for already running functions and for cached function invocations that have not begun yet.
    3. There would be significant amount of lead time before the function app is shutdown.
    4. The core work for implementation of the API is complete however upon testing i found some work needed in the service bus extension to handle `the stop watching traffic` state. 
- The core work for the drain mode API is complete is slated to begin deployment in the latest runtime release. Here is the related work item (https://github.com/Azure/azure-functions-host/issues/6268 and https://github.com/Azure/azure-webjobs-sdk/issues/2527) and release (https://github.com/Azure/azure-functions-host/releases/tag/v3.0.14228)
- The work on the service bus extension is in progress and can be tracked via this GitHub issue here: https://github.com/Azure/azure-functions-servicebus-extension/issues/95

**Comment by drdamour** [comment]
per https://github.com/Azure/azure-webjobs-sdk/issues/2795 cancellation tokens should no longer be triggered in drain mode, not sure of the status of this specific extension, but something to be aware of for anyone stumbling on this issue
