### ISSUE TITLE
Service bus session ordering guarantees with batch dispatch and multiple workers

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-functions-servicebus-extension#94]
A function app that is using the [FUNCTIONS_WORKER_PROCESS_COUNT](https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings#functions_worker_process_count) setting to configure multiple out-of-proc workers will not get in-ordered processing of service bus messages with sessions enabled if the function is configured to do batched dispatch.

Either we should find a way to fix (i.e. force all messages in the batch to be sent to the same worker) or fail to index the function.

**Comment by alrod** [comment]
@paulbatum, can you please clarify the issue? For session enabled SB entity we use [SessionClient](https://github.com/Azure/azure-functions-servicebus-extension/blob/dev/src/Microsoft.Azure.WebJobs.Extensions.ServiceBus/Listeners/ServiceBusListener.cs#L296) and [block](https://github.com/Azure/azure-functions-servicebus-extension/blob/dev/src/Microsoft.Azure.WebJobs.Extensions.ServiceBus/Listeners/ServiceBusListener.cs#L319) session on one worker during batch receiving.

**Comment by paulbatum** [comment]
You're right, since the entire batch is sent to a single worker, there is no issue here.

**Comment by alrod** [comment]
Chatted with @paulbatum offline and decided to close the issue.
