### ISSUE TITLE
Question: dependency on Microsoft.Azure.WebJobs.Sources

### ISSUE THREAD

**Issue by ModernRonin** [Azure/azure-functions-servicebus-extension#96]
Hi,

I was just wondering why you depend on Microsoft.Azure.WebJobs.Sources and if it would be possible to make that dependency private? 
It's not a big deal, it just looks odd in my current project where VS then shows me the Microsoft.Azure.WebJobs.Sources folder in solution explorer next to my own sources (might also be because I use paket, though).

Cheers,
Mark

**Comment by drdamour** [comment]
yeah...this is weird and an easy fix

**Comment by alrod** [comment]
latest https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.ServiceBus/5.3.0 does not the dependency to `Microsoft.Azure.WebJobs.Sources`
