### ISSUE TITLE
[ServiceBusListener.StartMessageBatchReceiver] Exception details not getting logged

### ISSUE THREAD

**Issue by tristan-earl** [Azure/azure-functions-servicebus-extension#97]
We're seeing the following error in our Application Insights logs:
`"An unhandled exception occurred in the message batch receive loop"`.

I found [this line in ServiceBusListener.cs](https://github.com/Azure/azure-functions-servicebus-extension/blob/8a01c68d16c5eeeda80010fd32f34d265eca9534/src/Microsoft.Azure.WebJobs.Extensions.ServiceBus/Listeners/ServiceBusListener.cs#L315), which logs the message along with the exception.  However, the exception details are not showing up in the logs.  I notice that this overload of `LogError` is being called:

`void LogError(this ILogger logger, string message, params object[] args)` 

...instead of this one:

`void LogError(this ILogger logger, Exception exception, string message, params object[] args)`

Since the Exception isn't explicitly passed in, I suspect it's just getting ignored.  I know when the latter overload is called, App Insights will track it as an exception.  Can this be changed so we get the full exception details in our logs?

**Comment by Zenuka** [comment]
Should be a simple fix, right?
