### ISSUE TITLE
Azure Function still able to fetch from queue when Service Bus is using a Private Endpoint

### ISSUE THREAD

**Issue by erwelch** [Azure/azure-functions-servicebus-extension#99]
I have an Azure Functions running on an elastic premium plan. One of our functions has a service bus trigger to a queue: 
```
  "generatedBy": "Microsoft.NET.Sdk.Functions-3.0.7",
  "configurationSource": "attributes",
  "bindings": [
    {
      "type": "serviceBusTrigger",
      "connection": "ServiceBusConnectionString",
      "isSessionsEnabled": true,
      "queueName": "%ServiceBusAudioQueueName%",
      "name": "messages"
    }
  ],
  "disabled": false,
  "scriptFile": "../bin/Osler.Teams.UploadService.dll",
  "entryPoint": "Osler.Teams.UploadService.ProcessAudio.ProcessAudio.Run"
}
```

I added a private endpoint for the ServiceBus. I verified it works with 2 other services we use (e.g. our AppService broke when it wasn't integrated into the VNET because it couldn't receive the messages).

However, with no VNET integration, no private endpoint, no relationship whatsoever to the VNET with the private endpoint - the Azure Function can still pull messages from the queue. It seems this should not be happening and getting 403 forbidden. Since I can only repro this with the FunctionApp and not an AppService I am curious if it might be something with this extension.

**Comment by sidkri** [comment]
@erwelch please provide the name of your function app so I can check its configuration.  Alternately, feel free to open a support request with this information.

**Comment by sidkri** [comment]
Closing the issue as there is no response for some time.  Please open a support ticket for this issue so our support team can investigate with you.
